### ISSUE TITLE
KIT station obs data not being retrieved

### ISSUE THREAD

**Issue by EricSaboya** [openghg/openghg#1001]
### What happened?

When running:
`openghg.retrieve.search_surface(site="KIT", store="obs_store", species="co2").results` 
on blue pebble. Results are shown for this dataset

However, 
`openghg.retrieve.get_obs_surface(site="KIT", store="obs_store", species="co2")`

Raises the following error: "ValueError: No site called KIT, please enter a valid site name."

Using OpenGHG "v0.6.2+169.g2ff819ff5.dirty"

Might work with the new zarr store? Site seems to be missing from "Supplementary Data" site-info.json file

### Environment

<details>

</details>

**Comment by gareth-j** [comment]
Have you tried `pip install -U openghg-defs`?

**Comment by gareth-j** [comment]
OK version 0.0.3 of openghg_defs is up on PyPI and the OpenGHG conda channel.
