### ISSUE TITLE
Store Datasource UUIDs with hash of file in storage class

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#1005]
At the moment we don't store the Datasource UUIDs that a file's data is assigned to. This can cause issues when we want to delete a Datasource and re-standardise some data. If we remove the hash then we don't know about some of the data that is still stored in the other Datasources. We could just store a list of UUIDs the data has been assigned to with the dictionary of hashes.

```python
hashes = {sha1_hash: [uuid1, uuid2, uuid3], ...}
```

When we want to delete a Datasource we can just remove its UUID from the list.

**Comment by rt17603** [comment]
Closed by #1025
