### ISSUE TITLE
Metadata - `AttributeError` when updating metadata mismatch

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#1028]
When I try adding `update_mismatch=True` to the call in #1027 I get the following error

```python
File .../openghg/standardise/meta/_metadata.py:91, in sync_surface_metadata(metadata, attributes, keys_to_add, update_mismatch)
     84 mismatch_keys = {
     85     "never": ["never"],
     86     "attributes": ["attributes", "from_source"],
     87     "metadata": ["metadata", "from_definition"],
     88 }
     90 for key, options in mismatch_keys.items():
---> 91     if update_mismatch.lower() in options:
     92         update_mismatch = key.lower()
     93         break

AttributeError: 'bool' object has no attribute 'lower'
```

**Comment by rt17603** [comment]
That error seems reasonable as the type for `update_mismatch` is `str` e.g. https://github.com/openghg/openghg/blob/devel/openghg/standardise/meta/_metadata.py#L60.

In general, we have been assuming people will pass the correct types based on the documentation and `bool` is invalid in this case. So we could catch this but it is a corner case at most.
