### ISSUE TITLE
Use openghg_defs to set lat/lon coordinates for data with a domain

### ISSUE THREAD

**Issue by brendan-m-murphy** [openghg/openghg#1046]
### What is your issue?

To avoid alignment issues, it would be useful to set the lat/lon coordinates for data with a domain when the data is added to an object store.

**Comment by qq23840** [comment]
Does someone have an example of a file for which this is a problem? @joe-pitt @brendan-m-murphy

**Comment by joe-pitt** [comment]
If you look in this object store ("/group/chem/acrg/object_stores/updated/shared_store_zarr") and run:
```
fp = retrieve.search_footprints(store=store,
                                species="hfo-1234zee",
                                model="NAME")
```

you'll see that the min_longitude is different for MHD compared to the others. I don't know whether all MHD fps for this species have the same coords, or whether this is dependent on the order in which they were loaded.
