### ISSUE TITLE
Footprint chunk test failing

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#1085]
### What happened?

We seem to be getting the following failed test when running the CI at the moment. One of the more recent PRs #1070 did update how the chunking was used when standardising footprint data but this test does pass locally.
```
FAILED tests/standardise/test_standardise.py::test_standardise_footprints_chunk - AssertionError: assert {'height': (2...e': (1, 1, 1)} == {'height': (2...time': (2, 1)}
```

### Environment

<details>

</details>

**Comment by brendan-m-murphy** [comment]
This passes for me locally, even after updating xarray.

**Comment by rt17603** [comment]
Seems to be related to upgrade of dask to `2024.8` - need to investigate but may need to pin `dask` version for now.

If unable to solve by end of day should pin.

**Comment by rt17603** [comment]
From @brendan-m-murphy investigations:

Issue caused by `sortby` operation - in latest version of dask 2024.8 this seems to change the chunks based on this operation. This happens in `_BaseData` when data is retrieved from the object store.

In most cases, sorting changes the chunk size, but it only changes the number of chunks by 1 (I think)... so for real world examples, it probably doesn't matter.
