### ISSUE TITLE
Remove parsers from OpenGHG for the data we have stopped processing.

### ISSUE THREAD

**Issue by SutarPrasad** [openghg/openghg#1089]
### What is your issue?

Currently, there are some deprecated sites for which we don't process any data. This means we have a lot of stale code for OpenGHG.

1. btt
2. cranfield
3. and more(please add here)

**Comment by SutarPrasad** [comment]
@rt17603 can you please add other unused parsers?

**Comment by rt17603** [comment]
Discussed on 19/09/2024:

We could potentially remove:
 - BEACO2N
 - BTT
 - CRANFIELD
 - EUROCOM
 - THAMES_BARRIER

Previously used for COP dashboard(?) but unlikely to be used again:
 - AQMESH ?? 
 - GLASGOW_LICOR ??
 - GLASGOW_PICARRO ??

**Comment by rt17603** [comment]
Before removing these parsers though we should:
 - Complete #1123 so we can add a nice tag for this
 - Tag the previous version before removing the parsers so we can easily get back to this if we want to.

**Comment by brendan-m-murphy** [comment]
Maybe we want to include in the docstrings info about the project each parser is for.

**Comment by rt17603** [comment]
Discussion with @mrghg on 23/09/2024

Keep:
 - BEACO2N

Remove:
 - BTT
 - CRANFIELD
 - EUROCOM
 - THAMES_BARRIER
 - AQMESH
 - GLASGOW_LICOR
 - GLASGOW_PICARRO

**Comment by rt17603** [comment]
Should we link the COP dashboard (https://github.com/openghg/dashboard) against a version of openghg which included the AQMESH and GLASGOW_* parsers?

Dashboard itself: https://openghg.github.io/dashboard/#/

**Comment by mrghg** [comment]
> Should we link the COP dashboard (https://github.com/openghg/dashboard) against a version of openghg which includes the AQMESH and GLASGOW_* parsers?
> 
> Dashboard itself: https://openghg.github.io/dashboard/#/

Sounds sensible
