### ISSUE TITLE
Improve standardisation of multiple footprints - monotonic error

### ISSUE THREAD

**Issue by alexdanjou** [openghg/openghg#1161]
### Is your feature request related to a problem?

Some footprints have some small error (order of 1e-8) in their stored longitude and latitude coordinates. When those errors are not the same across the footprints for a folder, this makes it impossible to standardise the folder all at once (e.g. `/group/chemistry/acrg/LPDM/fp_NAME/EUROPE/LIN-98magl/inert/`). The files have to be standardised one by one which seems less efficient (and less user friendly).

Standardisation attempt : 
```
from glob import glob
from openghg.standardise._standardise import standardise_footprint

standardise_footprint(filepath=glob(f'/group/chemistry/acrg/LPDM/fp_NAME/EUROPE/LIN-98magl/inert/*'),
                      site= 'LIN',
                      inlet= '98magl',
                      model= 'NAME',
                      met_model= 'UMG',
                      domain= 'EUROPE',
                      species='inert',
                      source_format= 'paris',
                      store= 'ad_test_zarr',
                      period= None,
                      continuous= True)
```

Error message : 
```
Traceback (most recent call last):
  File "/user/home/bq24992/workingDir/PARIS/Footprints/test.py", line 24, in <module>
    standardise_footprint(**kwargs)
  File "/user/home/bq24992/openghg/openghg/standardise/_standardise.py", line 621, in standardise_footprint
    return standardise(
           ^^^^^^^^^^^^
  File "/user/home/bq24992/openghg/openghg/standardise/_standardise.py", line 51, in standardise
    result = dc.read_file(filepath=filepath, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/home/bq24992/openghg/openghg/store/_footprints.py", line 371, in read_file
    footprint_data = parser_fn(**parser_input_parameters)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/home/bq24992/openghg/openghg/standardise/footprints/_paris.py", line 69, in parse_paris
    fp_data = xr_open_fn(filepath)
              ^^^^^^^^^^^^^^^^^^^^
  File "/user/home/bq24992/.local/lib/python3.12/site-packages/xarray/backends/api.py", line 1084, in open_mfdataset
    combined = combine_by_coords(
               ^^^^^^^^^^^^^^^^^^
  File "/user/home/bq24992/.local/lib/python3.12/site-packages/xarray/core/combine.py", line 958, in combine_by_coords
    concatenated_grouped_by_data_vars = tuple(
                                        ^^^^^^
  File "/user/home/bq24992/.local/lib/python3.12/site-packages/xarray/core/combine.py", line 959, in <genexpr>
    _combine_single_variable_hypercube(
  File "/user/home/bq24992/.local/lib/python3.12/site-packages/xarray/core/combine.py", line 645, in _combine_single_variable_hypercube
    raise ValueError(
ValueError: Resulting object does not have monotonic global indexes along dimension longitude
```

### Describe the solution you'd like

My suggestion is to make sure that the coordinates are perfectly aligned before trying to open them with `xarray.open_mfdataset`.

For example we could replace https://github.com/openghg/openghg/blob/3eca7392b0f170508509be2fbad46a6eaec2dd86/openghg/standardise/footprints/_paris.py#L70C1-L71C1 by something like : 
```

    try:
        fp_data = xr_open_fn(filepath)
    except ValueError as v :
        if not 'Resulting object does not have monotonic global indexes along dimension' in str(v):
            raise v

        import xarray as xr
        import numpy as np
        from openghg.util import align_lat_lon
        new_filepath = list()
        for file_name in filepath:
            with xr.open_dataset(file_name) as ds:
                ds_tmp = ds.rename({'longitude':'lon',
                                    'latitude':'lat'})
            lon,lat = ds_tmp.lon.values,ds_tmp.lat.values
            ds_realigned = align_lat_lon(ds_tmp,domain)
            lon_domain,lat_domain = ds_realigned.lon.values,ds_realigned.lat.values
            if np.sum(lon-lon_domain)!=0 or np.sum(lat-lat_domain)!=0 :
                split_file_name = file_name.split('/')
                split_file_name[-1] = 'tmp_'+split_file_name[-1]
                tmp_file_name = '/'.join(split_file_name)
                ds_realigned.rename({'lon':'longitude',
                                     'lat':'latitude'}
                                     ).to_netcdf(tmp_file_name)
                new_filepath.append(tmp_file_name)
            else :
                new_filepath.append(file_name)
        filepath = new_filepath 
        fp_data = xr_open_fn(filepath)
        pass
```

### Describe alternatives you've considered

In the example, every file is realigned and stored because they does not perfectly aligned with the referenced coordinates from the domain. However, they align between them except for one, so one other option would be to realign along the coordinated of the first file of the list (thus only one file should be stored in a tmp file).

Those solutions may not reduce the time of processing compared to processing the file one by one (haven't checked though). But may be simpler from a user perspective.

Let me know your thoughts so that I may go on and make (or not) some changes to the code.

**Comment by rt17603** [comment]
Great thanks Alex - that's really helpful and I think that looks like a good approach.

My only comment would be that I think it would be helpful to split out the bulk of those steps into a new function in the same module as the `align_lat_lon` function because this would also be really useful to include in other places as well (e.g. for the "acrg_org" format for instance).

I also wonder if rather than having to save a temp file we could save each re-aligned dataset within a list and then [concatenate](https://docs.xarray.dev/en/stable/generated/xarray.concat.html) these along the time axis when they've all been read?

But these are all pretty minor points, so feel free to put together a PR for this if you were happy to do so.

**Comment by alexdanjou** [comment]
Good point, I was afraid it would be too heavy but haven't tested. 
And the actual `for` loop is taking 15mn to process so I won't definitely merge this as it is..

I'll come back with a new proposition

**Comment by brendan-m-murphy** [comment]
You can pass a function to open mfdataset that will be applied before the data is combined, so that could be a place to align the lat/lon coordinates to the domain (Ben added a function to do this).

**Comment by brendan-m-murphy** [comment]
Also, Rachel's suggestion could work too, but I think open mfdataset has some extra code to make sure that computations are delayed (but that might be irrelevant here). Anyway, in this case, open mfdataset pretty much just concatenates the files (but is failing because the other coordinates aren't aligned).

**Comment by rt17603** [comment]
> Also, Rachel's suggestion could work too, but I think open mfdataset has some extra code to make sure that computations are delayed (but that might be irrelevant here). Anyway, in this case, open mfdataset pretty much just concatenates the files (but is failing because the other coordinates aren't aligned).

I think you're right that if we could do this directly through mf dataset in this case that would be better. Thinking about it, my concern on opening and concatenating would be that it would load the data all as one chunk rather than splitting this as it may have done with open_mfdataset.

We still may need to use something different again (e.g. opening separately and concatenating) for #1162 though.

**Comment by alexdanjou** [comment]
Whoa, I didn't know about this `process` argument of `open_mfdataset`.. Quite powerful indeed! Seems to work, fine and fast! I'll push something and make a PR once more thoroughly tested
