### ISSUE TITLE
Add `rank_data` attribute to `ObsData`?

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#117]

**Comment by rt17603** [comment]
So for this issue I guess the idea is to add an attribute to ObsData at the point when the ranking is set. We could also include an empty attribute (e.g. None) if no ranking is set as this could be useful information.

**Comment by rt17603** [comment]
It looks like `rank_metadata` is already added to the metadata for ObsData returned when the ranking is set - so I will close this issue now and we can open another, clearer one if something specific still needs to be added.
```
class SearchResults:
  ...
  def _create_obsdata(...)
    ...
    specific_source = self.results[site][species]
    rank_data = specific_source["rank_metadata"]
    ...
    if self.ranked_data:
        metadata["rank_metadata"] = rank_data
...
```
