### ISSUE TITLE
Missing sites - GCWERKS processing

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#12]
We have data for sites that OpenGHG doesn't know about.

```
aspendale
carnsore
empa
```

And some files that aren't recognized at all such as `sogeA-cawas.07.C`

Should we be able to process these files?

**Comment by mrghg** [comment]
I'll look into these. I think it's low priority, so we can ignore for now.

**Comment by gareth-j** [comment]
Closing this as these sites are not commonly used.
