### ISSUE TITLE
Failures when running tests locally - environment variable has to be set

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#129]
When running the tests locally, these will produce many failures and errors due to environment variables not being set:

FAILED tests/localclient/test_local_process.py::test_process_files - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
FAILED tests/modules/test_datasource.py::test_add_data - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
FAILED tests/modules/test_datasource.py::test_versioning - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
FAILED tests/modules/test_datasource.py::test_save - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
FAILED tests/modules/test_datasource.py::test_save_footprint - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
FAILED tests/modules/test_datasource.py::test_exists - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
FAILED tests/modules/test_datasource.py::test_from_data - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
FAILED tests/modules/test_datasource.py::test_load_dataset - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
FAILED tests/modules/test_datasource.py::test_in_daterange - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
FAILED tests/modules/test_datasource.py::test_shallow_then_load_data - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
FAILED tests/modules/test_emissions.py::test_read_file - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
FAILED tests/modules/test_eulerian_model.py::test_read_file - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
FAILED tests/modules/test_footprints.py::test_read_footprint - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
FAILED tests/modules/test_obssurface.py::test_read_CRDS - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
FAILED tests/modules/test_obssurface.py::test_read_GC - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
FAILED tests/modules/test_obssurface.py::test_read_cranfield - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
FAILED tests/modules/test_obssurface.py::test_read_beaco2n - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
FAILED tests/modules/test_obssurface.py::test_read_noaa_raw - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
FAILED tests/modules/test_obssurface.py::test_read_noaa_obspack - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
FAILED tests/modules/test_obssurface.py::test_read_thames_barrier - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
FAILED tests/modules/test_obssurface.py::test_upload_same_file_twice_raises - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
FAILED tests/modules/test_obssurface.py::test_delete_Datasource - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
FAILED tests/modules/test_obssurface.py::test_add_new_data_correct_datasource - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
FAILED tests/modules/test_obssurface.py::test_set_rank - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
FAILED tests/modules/test_obssurface.py::test_set_rank_overwrite - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
FAILED tests/modules/test_obssurface.py::test_rank_overlapping_dateranges - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
FAILED tests/modules/test_obssurface.py::test_rank_same_daterange_doesnt_change - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
FAILED tests/modules/test_obssurface.py::test_rank_daterange_start_overlap_overwrite - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/dataobjects/test_searchresults.py::test_retrieve_unranked - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/dataobjects/test_searchresults.py::test_retrieve_complex_ranked - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/localclient/test_get_surface_obs.py::test_get_observations_few_args - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/localclient/test_get_surface_obs.py::test_get_observations_with_average - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/localclient/test_get_surface_obs.py::test_get_observations_datetime_selection - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/localclient/test_get_surface_obs.py::test_gcwerks_retrieval - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/localclient/test_get_surface_obs.py::test_get_observations_fixed_dates - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/localclient/test_local_ranking.py::test_set_rank - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/localclient/test_local_ranking.py::test_passed_dates_and_dateranges_raises - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/localclient/test_local_ranking.py::test_clear_rank - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/processing/test_access.py::test_get_obs_surface - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/processing/test_access.py::test_no_inlet_no_ranked_data_raises - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/processing/test_access.py::test_get_obs_surface_no_inlet_ranking - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/processing/test_access.py::test_averaging_incorrect_period_raises - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/processing/test_access.py::test_timeslice_slices_correctly - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/processing/test_access.py::test_get_flux - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/processing/test_access.py::test_get_flux_no_result - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/processing/test_access.py::test_get_footprint - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/processing/test_access.py::test_get_footprint_no_result - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/processing/test_attributes.py::test_crds_attributes - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/processing/test_ceda_export.py::test_get_ceda_file_raises_no_args - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/processing/test_ceda_export.py::test_get_upload_file_json_file_output - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/processing/test_ceda_export.py::test_get_ceda_file_yaml_file_output - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/processing/test_ceda_export.py::test_get_ceda_file_return_dictionary - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/processing/test_ceda_export.py::test_get_ceda_file_height_correctness - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/processing/test_recombination.py::test_recombination_CRDS - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/processing/test_recombination.py::test_recombination_GC - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/processing/test_search.py::test_specific_keyword_search - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/processing/test_search.py::test_specific_search_gc - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/processing/test_search.py::test_unranked_location_search - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/processing/test_search.py::test_unranked_search_datetimes - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/processing/test_search.py::test_search_find_any_unranked - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/processing/test_search.py::test_ranked_bsd_search - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/processing/test_search.py::test_search_find_any - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/processing/test_search.py::test_search_incorrect_inlet_site_finds_nothing - ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store
ERROR tests/services/test_process.py::test_process_CRDS_files - ValueError: Error calling 'admin.setup' on 'registry': No ACQUIRE_HOST environment variable set
ERROR tests/services/test_process.py::test_process_CRDS_incorrect_args - ValueError: Error calling 'admin.setup' on 'registry': No ACQUIRE_HOST environment variable set
ERROR tests/services/test_process.py::test_process_GCWERKS_files - ValueError: Error calling 'admin.setup' on 'registry': No ACQUIRE_HOST environment variable set
ERROR tests/services/test_ranking.py::test_set_and_clear_ranking - ValueError: Error calling 'admin.setup' on 'registry': No ACQUIRE_HOST environment variable set
ERROR tests/services/test_retrieve.py::test_retrieve - ValueError: Error calling 'admin.setup' on 'registry': No ACQUIRE_HOST environment variable set
ERROR tests/services/test_searchfn.py::test_search - ValueError: Error calling 'admin.setup' on 'registry': No ACQUIRE_HOST environment variable set
ERROR tests/services/test_searchfn.py::test_search_and_retrieve - ValueError: Error calling 'admin.setup' on 'registry': No ACQUIRE_HOST environment variable set
ERROR tests/services/test_test_service.py::test_test_service - ValueError: Error calling 'admin.setup' on 'registry': No ACQUIRE_HOST environment variable set

**Comment by gareth-j** [comment]
This should now be fixed with #135 .
