### ISSUE TITLE
New NOAA sites

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#13]
I've added three new sites - PAO, AOC and WPC to the list of NOAA sites. These have no height or lat/long data associated with them as they're samples captured from onboard ships. Is this OK?

**Comment by mrghg** [comment]
I guess we don't need this info in the metadata for these mobile sites. However, we'll likely need to add variables to the data files, which provide the instantaneous lon/lat/height (which are in the data files). I think you can leave this as lower priority for now...

**Comment by gareth-j** [comment]
Once ObsMobile is completed and the mobile processing  functions are connected we can add these sites to the obsmobile metadata file.

**Comment by gareth-j** [comment]
This should also cover aircraft data.
