### ISSUE TITLE
Imports and use of file_search.find_files function needs to be updated

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#142]
The notebook (populate_object_store.ipynb) and script (populate_object_store.py) written to populate the object store within data files no longer work. Both files are within notebooks/data/ directory. This is specific to the `demo` branch,

The import statement used is:
`from openghg.localclient._file_search import find_all_files`
`all_inputs = find_all_files()`

The `find_all_files` has now been renamed to `find_files` and also now requires an additional input for the directory.

This needs to be updated.

**Comment by gareth-j** [comment]
Create `data_provider` repo and add this functionality to it.

**Comment by gareth-j** [comment]
This functionality is going to be moved to `openghg/populate`.
