### ISSUE TITLE
No units recorded on processing NOAA data

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#15]
Need to record units when processing NOAA data.

**Comment by rt17603** [comment]
We should look this up and add to the attributes for the NOAA data

**Comment by rt17603** [comment]
For the NOAA data I found that there are associated units in the input netcdf files (obspack) but that these were being lost when the dataset was converted to a pandas dataframe and back.

There is still a question around how to represent these units in the final output
 - Should "units" within the metadata be a particular format e.g. "ppb", "ppm" etc.
 - Should "units" for each data variable be 1e-9 etc., at the moment this is "mol mol-1" or "micromol mol-1"

**Comment by gareth-j** [comment]
Closing due to merged work.
