### ISSUE TITLE
Checking for single inlet in search error

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#151]
When we search for data from a single site with `search` the function checks how many inlets the site has. Currently it only doesn this for the known sites in the ACRG metadata file so this falls over then. Needs updating to be a bit more intelligent or just removing.

**Comment by rt17603** [comment]
I think this code has been commented out now. Is this something that we need specifically? And what was the primary reason for needing this?

PR #176 would include a change which checks if there is a single search result when the metadata is searched and bypasses the ranking steps. This may achieve some of the original aims of this check.

**Comment by rt17603** [comment]
This is the commented out code:
```
    # TODO - Update this as it only uses the ACRG repo JSON at the moment
    # Check if this site only has one inlet, if so skip ranking
    # if "site" in search_kwargs:
    #     site = search_kwargs["site"]
    #     if not isinstance(site, list) and not multiple_inlets(site=site):
    #         skip_ranking = True
```

**Comment by rt17603** [comment]
@gareth-j - I assigned you back to this issue to get your thoughts on the above comments/questions

**Comment by gareth-j** [comment]
Yeah I think we can just remove this. We should expect some ranking data to be set or the inlet to given by the user I think.

**Comment by rt17603** [comment]
I agree, in the case where there are multiple inlets but we don't want to have to specify the inlet if there is only one.

Regardless, I think PR #176 covers that case indirectly by skipping the ranking when only one value is returned so I think this can be closed.
