### ISSUE TITLE
Specification for data types

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#160]
We could do with a spec document for the data types that OpenGHG expects.

Using the DataSchema method we should implement data schemas for all data objects:

- [x] ObsSurface
- [x] Footprints
- [x] Emissions
- [x] Boundary Conditions
- [ ] #390
- [ ] #391

and continue to implement this as standard for all new data objects.

**Comment by gareth-j** [comment]
We need users to know the type of data we expect to be available in footprint, emissions etc data.

**Comment by gareth-j** [comment]
I'm re-assigning this to the February milestone as this will take input from @rt17603  and @mrghg.

**Comment by rt17603** [comment]
Could incorporate this as `format` method/attribute for each of the input objects (e.g. `ObsSurface`, `Footprint`, `Emissions`, `BoundaryConditions`, `EulerianModel`) and then build up the spec from this method.

e.g. For `BoundaryConditions` class

```
    @staticmethod
    def format() -> Dict[str, Any]:
        """
        Define format for boundary conditions Dataset.
        TODO: Implement this!
        """
        dims = ["lat", "lon", "time", "height"]
        data_vars = {"vmr_n": ("time", "height", "lon"),
                     "vmr_e": ("time", "height", "lat"),
                     "vmr_s": ("time", "height", "lon"),
                     "vmr_w": ("time", "height", "lat")
                     }
        data_types = {"lat": np.float32,
                      "lon": np.float32,
                      "height": np.float32,
                      "time": np.datetime64,
                      "vmr_n": np.float64,
                      "vmr_e": np.float64,
                      "vmr_s": np.float64,
                      "vmr_w": np.float64,
                      }

        data_format = {"dims": dims, "data_vars": data_vars, "data_types": data_types}

        return data_format
```

**Comment by rt17603** [comment]
Links to PR #331

**Comment by rt17603** [comment]
Using the DataSchema method we should implement data schemas for all data objects:

- [ ] ObsSurface
- [ ] Footprints
- [ ] Emissions
- [ ] Boundary Conditions
- [ ] Eulerian Model

and continue to implement this as standard for all new data objects.

**Comment by rt17603** [comment]
Closing as this is umbrella issue for the data types with the remaining tasks already separated into their own issues.
