### ISSUE TITLE
Tests fail if ACQUIRE_HOST not set

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#178]
When running most tests, these will fail with an error that `ACQUIRE_HOST` is not set.

For example (I was creating a new test):

`$ pytest -v tests/retrieve/test_access.py::test_timeslice_slices_correctly_exclusive`

```
FAILED tests/retrieve/test_access.py::test_timeslice_slices_correctly_exclusive - ValueError: No ACQUIRE_HOST environment variable set
```

This can be temporarily bypassed (until terminal etc restarts) by setting `ACQUIRE_HOST` to be anything e.g.
$ export ACQUIRE_HOST=0

but this does need to be fixed as user shouldn't need to do this to be able to run the tests.

**Comment by gareth-j** [comment]
This is done with #184.

**Comment by rt17603** [comment]
I've pulled the latest version of `devel` and I still get this error if I try and run the tests using pytest. For reference to run all the tests, I ran the following command in a terminal through VS Code on BP1 from within the `openghg` repository.
```
$ module load lang/python/anaconda/3.8.8-2021.05-2.5
$ source /user/home/rt17603/work/environments/openghg_env/bin/activate
$ pytest -v
```
