### ISSUE TITLE
Duplicate time values returned from get_obs_surface

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#190]
When using `get_obs_surface()` to retrieve data, if the date range overlaps multiple ranking periods data for multiple inlets is  sometimes returned with duplicate time points.

For the test set up within tests/retrieve/conftest.py using e.g.
```
    obsdata = get_obs_surface(site="bsd", species="ch4")
```
exhibits this behaviour.

Illustrated by `tests/retrieve/test_access.py::test_get_obs_surface_ranking_unique` within `mult_inlet` branch (this branch will be merged into devel with PR#192). This is currently set up an an `xfail` (expected fail) so we know how to test this and see if we can fix the bug.

**Comment by gareth-j** [comment]
Fixed with #256.
