### ISSUE TITLE
Create easily accessed list of data types which can be processed

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#196]
This can be added to the beginner tutorial to present the user with a list of options. Could be returned as a DataFrame perhaps linked to the sites associated with each data_type.

**Comment by rt17603** [comment]
Should also do this for site codes

**Comment by rt17603** [comment]
Can link to at least:
 - data/lghg_sites.json
 - data/beaco2n__site_data.json
 - data/process_gcwerks_parameters.json (but may need extra instrument details on top of this)

**Comment by rt17603** [comment]
Links to PR #226

**Comment by gareth-j** [comment]
Done with #226.
