### ISSUE TITLE
Missing metadata / attributes for standardisation modules

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#201]
These modules have missing data that maybe should be present in the metadata / attributes

### Metadata

- [x] BTT - inlet, instrument

### Attributes

- [ ] Cranfield - no attributes
- [x] CRDS - 'sampling_period', 'instrument'
- [x] NOAA - ObsPack flask data -  'instrument'

**Comment by rt17603** [comment]
I'm a little confused about Cranfield and the associated site code - in the "site_lookup.json" file there's a value for "THB" and "TMB" (Thames Barrier) but in the "acrg_site_info.json" file the only site associated with the CRANFIELD network is "TMB" (Thames Barrier).

So should the references to "THB" actually be "TMB"? I don't know anything about data from Cranfield but is this actually just another set of data from the Thames Barrier or is this something different?

**Comment by rt17603** [comment]
Not completed by PR

**Comment by rt17603** [comment]
Response from Daniel on 08/02

*Initial question: Would you mind if I clarified some details with you about how we're receiving the London GHG data? I'm just trying to work out what modules we need for openghg around Cranfield and Thames Barrier versus the other sites*

> in summary: the Cranfield (LICOR instruments) and thames barrier data gets uploaded to a dropbox folder, then I manually download and process them (the licor file format sometimes changes slightly then I need to change the process code in the repo...)

*Question: So if that going to be the ongoing situation - the thames barrier data being supplied by cranfield?*

> I believe so, I don't know how long the thames barrier data will be ongoing. The LICOR data is the LGHG specific instruments, then any other London sites we get access to is on an ad-hoc basis

**Comment by rt17603** [comment]
@gareth-j - for Cranfield can you add a NotImplementedError (or otherwise) so we can come back to this if we get more details.

**Comment by gareth-j** [comment]
Closing, deprecation warnings will be added for the BTT and Cranfield standardisation functions: #770.
