### ISSUE TITLE
Remove warning about missing keys

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#229]
The key missing warning such as

```
WARNING: long_name key not in attributes or metadata
```

Should be changed so it either logs something or doesn't print at all, it results in too much being printed to screen.

**Comment by rt17603** [comment]
So, I added that in the one of the recent PRs - it's printing out the warning when cross referencing the attributes and metadata. How would you want any logging etc. to be done? And we can go through and make sure these keys are present so it doesn't print out the warning? (linked to Issue #201 )
