### ISSUE TITLE
Use of old_div in footprint merge

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#23]
Do we need `old_div` here? Does it matter if we get floats using Python 3 division?

https://github.com/openghg/openghg/blob/029fb16183b0f4abdbc99c685af207a7e02e8754/openghg/processing/_process_footprint.py#L95

**Comment by mrghg** [comment]
I suspect this was something that was added when we moved from python 2 to 3. Fairly sure it can safely be removed...

**Comment by rt17603** [comment]
Yes, that was added when we used the future module on the code - no issue with it being replaced with a standard division (carefully!) as I believe this was just the future module being cautious.

**Comment by gareth-j** [comment]
This was fixed in #25 .
