### ISSUE TITLE
Combine `site_lookup` and `acrg_site_info` into a single JSON

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#266]

**Comment by rt17603** [comment]
At the moment there are a few different places site is checked using different files:
 - `openghg.utils.verify_site` uses `site_lookup.json` and is called within (at least) `ObsSurface.read_file` function
 - `openghg.retrieve.get_obs_surface` uses `acrg_site_info.json` and does not allow lookups for sites not included in this file
    - `openghg.retrieve.search_surface` does not include the same restriction

**Comment by rt17603** [comment]
Links to PR #490 but this does not full close this issue.

**Comment by rt17603** [comment]
- [ ] Remove unused files related to sites and consolidate details - PR #490 
- [ ] Incorporate any useful details from `site_lookup.json` into `site_info.json`
- [ ] Update `openghg.utils.verify_site` to use `site_info.json`

**Comment by gareth-j** [comment]
Should we close this as things are being moved?

**Comment by rt17603** [comment]
I left this open at the moment as `site_lookup.json` is still within openghg and `verify_site` still uses this. We can split this out into a new issue for clarity and close this one.

**Comment by rt17603** [comment]
Opened #534 to cover the remaining spin off issues for this.
