### ISSUE TITLE
Add ability to process multiple emissions / flux / BC files at once

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#267]
At the moment `Emissions.read_file` only takes a single emissions file, we should bring this in line with ObsSurface.

**Comment by gareth-j** [comment]
@brendan-m-murphy could these changes be imlpemented with your changes to the standardise functions?

**Comment by rt17603** [comment]
This is also related to the discussion on PR #1164 links to the changes made around the `check_function_open_nc` which is the function which could be used to allow multiple files to be opened at once.

This may be superceded by #1169 if this is the route we want to go down for allowing multiple files to be opened at once.
