### ISSUE TITLE
Update `get_` functions to all raise a ValueError when no data can be found / too much data is found

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#297]
Update `get_` functions to all raise a ValueError when no data can be found / too much data is found
    - If no data is found, make sure this (and keywords asked for) is clear (could include search command details here to assist?)
    - If > 1 set of data is found and ranking IS NOT present / used, print message to suggest adding ranking or being more specific
    - If > 1 set of data is found and ranking IS present / used, print message to suggest improving ranking details

**Comment by rt17603** [comment]
May want to change this so they all return `ValueError` like `get_obs_surface` - if taking the "programmatic approach" to the get functions versus the search and retrieve steps

**Comment by rt17603** [comment]
Updating the name for this to reverse original decision to make this return None based on more recent updates.

**Comment by rt17603** [comment]
**Will need to update ModelScenario to catch these errors when they occur and print details from the error, as this can continue even if this fails**
