### ISSUE TITLE
ObsSurface.readfile throws error for GCWERKS, if scale or units missing from header

### ISSUE THREAD

**Issue by mrghg** [openghg/openghg#3]
For example, capegrim GC data files contain some non-standard species, measured on the PDD instrument. The species name is something like "Ne_PDD", and there is no corresponding unit or scale. This causes the whole processing script to fail. 

In my local processing routines, I have a species_translator function that renames the species (i.e. {"Ne_PDD": "Ne", etc.}), and doesn't error when encountering no scale or unit.

To be safe, for now I think we should just ignore these columns, rather than processing something without a unit or scale. 

To recreate:

```python
filepath = sorted(glob("/path/to/capegrim.*[!s].C"))
filepath_precision = sorted(glob("/path/to/capegrim.*precisions.C"))

files = [(f, fp) for f, fp in zip(filepath, filepath_precision)]

agage_results = ObsSurface.read_file(filepath=files, data_type="GCWERKS", network="AGAGE")
```

**Comment by gareth-j** [comment]
These errors are now fixed by #7. I'll get all the other files from BP1 processed and will open another issue if I find any other issues.
