### ISSUE TITLE
Add sampling period to observation files

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#30]
A "sampling period" variable needs to be added to all observation files. This indicates the time period the measurement from the raw observation files represents.

**Comment by rt17603** [comment]
Do we want to include a default for this (perhaps 1 hour - "1H")?

**Comment by mrghg** [comment]
Perhaps it's better to make this assumption in the code? I.e. if there's no "sampling_period" variable/attribute, just assume 1H, and flag up some kind of warning? If it gets into any data files, then there's a danger it gets propagated.

**Comment by rt17603** [comment]
Ok, sounds like a better approach. I'll add a note to the Issue related to this being implemented within the footprints data merge code.

**Comment by rt17603** [comment]
Links to PR #63

**Comment by rt17603** [comment]
This functionality has been added and merged. The remaining work to be completed is covered by Issue #84.
