### ISSUE TITLE
Add ability to add 1D emissions timeseries (e.g. global total)

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#301]
Want to allow emissions timeseries data to be added to the object store and plotted. May want to set this up as a new class or something based on current classes.

**Comment by rt17603** [comment]
This could be generalised to be just a 1D timeseries object to allow for more flexible inputs to be run.

**Comment by SutarPrasad** [comment]
Comments from @rt17603 are added here to keep track of the discussion.
So you can use something like the BoundaryConditions class as a starting point for this - https://github.com/openghg/openghg/blob/devel/openghg/store/_boundary_conditions.py
_boundary_conditions.py
openghg/openghg

It'll be another class within the openghg/store sub-module and will have basically the same methods but with the implementation for your 1D emissions class.

For this we'll need to decide on what we want the 1D emissions data to look like when it's stored in OpenGHG. It may be worth looking at the 1D emissions data produced by InTEM for this as a starting point and we can refine and discuss as needed.
