### ISSUE TITLE
Update `get_*` functions to avoid the try except each time

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#326]
We should be able to do 

```
if results:
    ...
else:

```

**Comment by rt17603** [comment]
@gareth-j - Has this been superceded now by more recent updates to get functions? If not, do we still have a sense of what would need to be updated here?

**Comment by rt17603** [comment]
@gareth-j - Is this issue still relevant or has this been superceded by later updates? What would need to be updated with this one?
