### ISSUE TITLE
Stop supporting Python 3.7

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#344]
I'm coming across some features that aren't supported in Python 3.7 and seeing as it's quite old I think we can drop support and move to support 3.8 -> 3.10 instead.

**Comment by rt17603** [comment]
@gareth-j - can this issue be closed?

**Comment by rt17603** [comment]
@gareth-j - Can this issue be closed? We're no longer running the CI against 3.7, [only 3.8, 3.9, 3.10](https://github.com/openghg/openghg/blob/devel/.github/workflows/workflow.yaml#L20) so I assume this is no longer supported?

**Comment by gareth-j** [comment]
Yeah that can be closed.
