### ISSUE TITLE
Decide how to allow users to update stored metadata (e.g. site data)

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#346]
### What is your issue?

Ultimately for this to a viable tool to use in the long term we need to consider how users can add to or update our stored metadata (i.e. site_info.json etc.). This includes details like new sites, new species, (new domains) and updating existing metadata e.g. the name of data owners or just correctly mistakes.

This could also depend on where our metadata is stored. For example we can decide if we want to keep this within the openghg library or if this could be stored elsewhere and pulled by our openghg library as needed.

Depending on the decided approach, updates could be:
 - formally through a PR
    - *Note: This would require our users to have a copy of the code rather than just install the openghg library through pip/conda*
 - a provided tool of some kind
    - This may link better with metadata being stored elsewhere.

We could also have a copy of e.g. the site_info.json file added to any new object store which could then be updated by the user as needed (through written tools or directly).

**Comment by gareth-j** [comment]
We could also have a function that gets the new version of the metadata file ready to submit as an issue.
Or could we just diff theirs and ours, do some checks and submit the diff as an issue / PR?

**Comment by rt17603** [comment]
This data has now been moved onto a separate repository and can be updated there using PRs going forward - https://github.com/openghg/supplementary_data
