### ISSUE TITLE
Check start, end date behaviour on get_* functions

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#353]
```
xarray/core/indexes.py:97: FutureWarning:

Indexing a timezone-naive DatetimeIndex with a timezone-aware datetime 
is deprecated and will raise KeyError in a future version.  Use a timezone-naive object instead.
```

**Comment by rt17603** [comment]
Is this warning still being printed? If I run the tests on the command line (with -s) I can't see it in there but was there another way to produce this?

**Comment by gareth-j** [comment]
Running tests in `tests/analyse/test_scenario.py` results in these warnings.

**Comment by rt17603** [comment]
@gareth-j - what version of xarray are you running with when you get these warnings?
