### ISSUE TITLE
Difference between `retrieve` and `get_obs_surface` - mf or species name

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#354]
At the moment the search / retrieve functions return Datasets that have the species name in the Dataset whereas `get_obs_surface` changes the species name to `mf`. Which one do we want to keep?

**Comment by rt17603** [comment]
Yes I believe we have decided this reasonable. The `retrieve` functions give back the data as it is stored but the `get*` functions can apply some updates to the data (e.g. as needed for inversions).

We have also added the ability to not rename the variables to "mf*" if needed within PR  #1130
