### ISSUE TITLE
`station_latitude` or `latitude`

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#370]
We seem to have differences in how we store lat/lon data in attributes and metadata. We should make sure this is standardised across surface types.

**Comment by rt17603** [comment]
From external discussions, I think we should make sure this is stored in the metadata as "station_latitude" etc. This is because the new AGAGE format will include "inlet_latitude" etc. and so would be good to make sure we're distinguishing.

**Comment by SutarPrasad** [comment]
I checked in the code and there is already at some places station_latitude included. So do we need this issue? Or have we identified this issue for occurrences of it in some places? @rt17603

**Comment by rt17603** [comment]
This is mainly about making sure this is done consistently for all our surface parse_* functions.

**Comment by SutarPrasad** [comment]
I investigated all the parse functions and currently, we are storing the metadata and attributes with the station_* prefix. hence this won't require any changes for now.
