### ISSUE TITLE
What should `get_obs_surface` do when there's no results?

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#380]
At the moment it raises a `ValueError` which I feel might be a bit much. Return `None`?

**Comment by rt17603** [comment]
Let's keep this as raising a `ValueError` - that ties in better to the "programmatic view" of this function (compared to search). For the search function this shouldn't return a ValueError but just a None type ouput (e.g. still `SearchResults` object but prints a None or something).

Just need to make sure the error message is informative.
