### ISSUE TITLE
Code retreat issues

### ISSUE THREAD

**Issue by mrghg** [openghg/openghg#395]
Summary of issues found at the code retreat in August

**Comment by ag12733** [comment]
In the instructions, after the step where you run ipython and try to import openghg - it will work, however will throw up an error that ValueError: No environment variable OPENGHG_PATH found, please set to use the local object store.  Update the instructions to note that this is ok.

**Comment by mrghg** [comment]
Edit install instructions to say that conda-build should be installed using conda-forge

**Comment by mrghg** [comment]
nbformat not in environment.yml or requirements.txt, but needed for plotly?

**Comment by EricSaboya** [comment]
Option for using station data (e.g. Mace Head) for baseline when comparing simulations with measurements.

**Comment by EricSaboya** [comment]
Percentile baseline data: i) option to change percentile value in scenario.plot_comparison() and ii) to calculate percentile value using daytime data only

**Comment by mrghg** [comment]
searching is quite slow. Reads all datasources, rather than db?

**Comment by mrghg** [comment]
When processing new obs data, streamline the warnings. You get lots of lines saying:
```
NOTE: Combining overlapping data dateranges
NOTE: Dropping measurements at duplicate timestamps
```

**Comment by mrghg** [comment]
Need a method to delete things from the object store easily

**Comment by mrghg** [comment]
Remove "units" from metadata. Currently, defined inconsistently (e.g., "nmol mol-1" in ICOS, nothing for CRDS, and "ppb" for GCWERKS). Use unit in data frame instead

**Comment by hanchawn** [comment]
CO2 always defaults to high_time_res = True, would be useful to set to False sometimes when flux time res is e.g. daily (e.g. ocean fluxes)

**Comment by rt17603** [comment]
> Install instructions don't mention the need to set the OPENGHG_PATH environment variable

[mrghg](https://github.com/mrghg) commented [on 31 Aug](https://github.com/openghg/openghg/issues/395#issue-1357109229)

**Comment by rt17603** [comment]
Have now moved all comments out into issues so will close this umbrella issue.
