### ISSUE TITLE
Add simple local user config

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#398]
We could do with a terminal function to setup a local user config which sets the local object store path, the main user object store and a user object store. Then we could just use group permissions to control writing to a main object store. A user could then set a path to their own store and anything they processed to their own local store.

- `openghg setup`
- Ask for user input for main object store, path for user object store
- Writes to a ~/.config/openghg.conf file
- Update search to search different object stores?
- Will we need to update the `SearchResults` object?

**Comment by rt17603** [comment]
@gareth-j - does this link to your #521 PR around adding the openghg quickstart or would this be something in addition to that?

**Comment by gareth-j** [comment]
Yeah I think that PR will close this
