### ISSUE TITLE
Improve search - multiple types

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#401]
- Return a pandas DataFrame
- Search each data type
- Search only metadata store instead of loading all the Datasources

**Comment by gareth-j** [comment]
Working on this with #418.

**Comment by rt17603** [comment]
This could be called through a generic `search()` function which accepts `data_type` as an input. If no `data_type` input is supplied this will search using the keywords for all data types and return a pandas DataFrame with "data_type" as the first column.

**Comment by gareth-j** [comment]
Done with #414 and #418
