### ISSUE TITLE
retrieve_icos not defined 

### ISSUE THREAD

**Issue by amarmistry1** [openghg/openghg#409]
### What is your issue?

When running the retrieve_icos function, the following error message appeared;

NameError: name 'retrieve_icos' is not defined

**Comment by rt17603** [comment]
Did you have any more information on how to reproduce this error? If not, is it ok if we close this?

**Comment by rt17603** [comment]
@amarmistry1 - I'm going to close issue as we can't currently reproduce this (and I believe we managed to resolve this on the Code Retreat?) If you do still encounter this problem please do feel free to open another issue with some more details and we can prioritise it.
