### ISSUE TITLE
Add a metadata store when SearchResults is returned

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#411]
At the moment when we want to retrieve data using the `retrieve` method we can only pass in the site, species and inlet, we can't be more specific. If we add a small metadata store with created from the returned results we can make the search far more flexible. This will also allow us to use the `SearchResults` object when returning flux, emissions etc.

**Comment by gareth-j** [comment]
Instead of adding a metadata store I've added a function that searches through the metadata. As we won't have THAT much metadata I think that's fine. See #414.

**Comment by rt17603** [comment]
Was this closed by #414 or #418?
