### ISSUE TITLE
Update SearchResults use pretty print when print() function is called

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#432]
Make printing out SearchResults use pretty print (i.e. how Jupyter notebooks prints pandas DataFrames)

**Comment by SutarPrasad** [comment]
Now that we have included a **rich** Library, shall we make the most of it to have user-friendly console outputs? Compatible with Jupyter too.

**Comment by rt17603** [comment]
Prasad Sutar 29/06 12:38: 
[This is the output of the rich table]

<img width="1392" alt="MicrosoftTeams-image (2)" src="https://github.com/openghg/openghg/assets/37222223/5043ee7b-ac04-4da7-bd0f-4c9d1d03752c">

Prasad Sutar 29/06 12:38: 
How much of significance is the uuid column inside df? Its actually taking lot of space and I am struggling with the visual formatting. [...] if this isn't significant i was thinking of dropping it.

**Comment by rt17603** [comment]
Prasad Sutar :0/06 10:20
I managed to find out a workaround for that table thing. Something like this will be the output if the columns are over 5. And cross checked with the dictionary that gets imported and it shows all the information without missing any values.
<img width="1512" alt="MicrosoftTeams-image" src="https://github.com/openghg/openghg/assets/37222223/11b7bcd2-48e0-4e49-874f-f1144dd06377">

**Comment by rt17603** [comment]
@SutarPrasad A few things I just want to check:

As I can't see on this screenshot, is this output produced using something like this?
```
results = search_surface(network="noaa")
print(results)
```

After the printed table, does the output to screen also include the following line?
```
Found ... results.\nView the results DataFrame using the results property.
```

**Comment by SutarPrasad** [comment]
> @SutarPrasad A few things I just want to check:
> 
> As I can't see on this screenshot, is this output produced using something like this?
> 
> ```
> results = search_surface(network="noaa")
> print(results)
> ```
> 
> After the printed table, does the output to screen also include the following line?
> 
> ```
> Found ... results.\nView the results DataFrame using the results property.
> ```

<img width="954" alt="image" src="https://github.com/openghg/openghg/assets/75735315/de8d6b53-e73c-462b-8acb-c9b7a1103de3">

Also just writing print(results) generates below output:
<img width="954" alt="image" src="https://github.com/openghg/openghg/assets/75735315/18c8b629-7ba0-4dd9-b6ed-2dc0bf5abc9f">

**Comment by joe-pitt** [comment]
Yes that print option look great - thank you! It is nice that we could still chose between the two formats by selecting either print() or .results
