### ISSUE TITLE
Compression on standardised NetCDF store

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#457]
At the moment we don't do any kind of compression on write out of NetCDF. This could easily be added with the `encoding` agument to `to_netcdf`.

**Comment by gareth-j** [comment]
@EricSaboya has been adding a lot of footprints to a group object store. Using the scripts used to populate this store would be a useful way of testing the diffrent zarr compression algorithms.

**Comment by rt17603** [comment]
Duplicate of #296
