### ISSUE TITLE
search_surface can't find results if an inlet is given.

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#478]
> Related to this, search_surface can't find results if an inlet is given.

> This code:
> search_results = search_surface(site='TAC',
                 species='co2',
                 inlet='185',
                 start_date='2018-01-01',
                 end_date='2018-02-01'
                 )

> Gives this warning:
> WARNING:openghg.retrieve:No data found for the dates given, please try a wider search.

> Using the code above without a start_date and end_date does not return a warning but also does not return any results.

_Originally posted by @hanchawn in https://github.com/openghg/openghg/issues/477#issuecomment-1307248897_

**Comment by hanchawn** [comment]
That says 185.0

**Comment by rt17603** [comment]
Yeah so the issue here was that it was interpreting this float from the file and storing this as "185.0m" which then wasn't being found by the "185", "185m" etc. searches. I've updated the `format_inlet` functionality now to make sure any inlets which can be cast to an integer are stored without any decimal places. When PR #480 goes in this issue should be fixed.
