### ISSUE TITLE
Ensure syncing of the Jupyter notebook and markdown versions of the tutorials

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#487]
For each created Jupyter notebook tutorial this also has an accompanying markdown copy which is used for the documentation pages. However, these seem to have gotten out of sync in the latest version on devel.

Need to check
 - [ ] These should be synced as part of the .github/workflow/ but maybe not committed?
 - [ ] jupytext can be run within precommit. If this is the best way to do this, does this need to be updated so everyone can use this?
 - [ ] Can we ensure that ipynb --> md AND md --> ipynb is run depending on which file has been updated?

**Comment by gareth-j** [comment]
This can be closed now as we've moving to restructured text based notebooks with #518
