### ISSUE TITLE
Differentiating between versions of emissions files for same year-species-domain when adding/retrieving from the object store 

### ISSUE THREAD

**Issue by EricSaboya** [openghg/openghg#489]
### What is your issue?

When using `standardise_flux()` there is not currently an option for being able to differentiate between versions of emissions files that are of the same species, year and domain. For example, if there are emissions data of CH4 for the year 2019 gridded to the EUROPE domain from both EDGARv6.0 and EDGARv7.0 there is not an option to distinguish between these datasets when retrieving them from the object store. Having this option would be really helpful. 

I found that you can distinguish between such data if using different strings for the `source` argument in `standardise_flux`. This could be problematic when having a large number of emissions files in the object store and having to recall the different source arguments assigned. 

I found if both data files of the same domain-year-species are added to the object store using the same `source`  argument, a merged emissions dataset is retrieved from the object store with dimension that does not match the domain of interest. This exactly happened when adding the 'ch4-ukghg-edgar5-2019.nc' and 'ch4-ukghg-edgar7-2019.nc' files (for total emissions) to the object store and using `source='total'` for both emissions files. 

Having an additional argument or two in `standardise_flux` seems like it would be the most pragmatic approach to resolving this.  Maybe an argument such as `data_version` to distinguish between the version of EDGAR but also  `embedded_emissions=True/False` as a way of indicating whether UKGHG emissions have been nested into EDGAR over the UK (this might have to be generalised).

**Comment by rt17603** [comment]
Note on "embedded_emissions": we could consider that fundamentally the "domain" is different between e.g. the whole of Europe at one resolution and Europe with an embedded UK map and use this to differentiate in some way.

**Comment by rt17603** [comment]
Flux
----

Add:
 - inventory name
 - inventory version
 - apportionment - source sector
 - model

Also consider:
- embedded inventory - multiple inventories
- multiple inventories - True/False
- sector naming mapping between naei, edgar

Boundary conditions
-------------------

bc_input
- model
- inventory
- setup

**Comment by rt17603** [comment]
Meeting on 08/12/2022 at 10am:
 - Another consideration here is our expectation around which flux / emissions data will be stored in the object store. This should influence what keywords we expect
 - Rather than combined inputs etc. this should be derived from underlying models / databases e.g. EDGAR, GFED etc.
