### ISSUE TITLE
Unable to retrieve boundary conditions files

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#491]
After adding boundary conditions files to the object store, they were then not being retrieved when the `get_bc` function was used:

<img width="1512" alt="Screenshot-2022-11-25-at-10 03 52" src="https://user-images.githubusercontent.com/37222223/204267532-a721f20a-bf14-489c-999e-fda9b7952c41.png">

From further investigation it was reported that:
> I was able to see the BC files I'd added using search but they had data_type=NaN (indeed no results were given for search_bc).

So the data_type was not set correctly for some reason. This should be "boundary_conditions"

**Comment by EricSaboya** [comment]
`standardise_bc` indicates BC files already added to object store. `openghg.standardise.search_bc().results` gives an empty DataFrame but `openghg.standardise.search().results` shows these files are in the object store but with a NaN data_type. 

NB. This was not a problem when previously adding these files but problem occurred when pulling new openghg update.

**Comment by EricSaboya** [comment]
I was able to resolve this issue by deleting all files from my object store and re adding them. I believe the updated in the data_type terms may have been the cause of this problem

**Comment by rt17603** [comment]
Not an issue with the new version
