### ISSUE TITLE
Pass in additional metadata when standardising data

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#493]
As long as the additional metadata doesn't clash with the required kwargs we should accept it.

**Comment by rt17603** [comment]
@gareth-j - was there an example of this? Or was this just a call to add e.g. kwargs to the input options?

**Comment by gareth-j** [comment]
This was so users could pass in custom metadata when standardising data. I guess so people could add personalised tags to data etc. This is in addition to the required keys that we use and may specify in a config file in the future - see #757. Would it be useful for users to add a key value pair of `"project" = "gemma"` or something when standardising data?

**Comment by rt17603** [comment]
Ok, so the initial implementation we talked about could be adding **kwargs to all standardise functions AND making sure any additional unrecognised keys are used as additional initial metadata search and store terms.

Then it sounds like "config file in the future - see https://github.com/openghg/openghg/issues/757" could be another step beyond this. Depends on how we want the interface to be presented to the users.

**Comment by gareth-j** [comment]
I think this can be link to the object store configuration issue #757

**Comment by gareth-j** [comment]
After our discussion yesterday we'll move to using the `optional_metadata` dictionary method to add optional metadata.
