### ISSUE TITLE
Retrieving from ICOSCP - multiple datasets match criteria

### ISSUE THREAD

**Issue by joe-pitt** [openghg/openghg#494]
### What happened?

I've been retrieving data from the ICOS CP, for example:
wao_data_level2 = retrieve_atmospheric(site="WAO", species="CH4", data_level=2)

The problem is that there are three L2 CH4 datasets for WAO on the CP (all with the same inlet height) - the ICOS dataset, the InGOS dataset and the OBSPACK-Europe dataset. The code above returns only the OBSPACK-Europe dataset, and does not appear to have an option to specify an alternative. Most sites have at least two different files with the same species, level and inlet height - it is important that the user is able to choose between them.

After some digging, it seems to me like `_retrieve_remote` loops through the `dobj_urls` (starting L270), and overwrites data if "spec" and "inlet" are the same (which they will be for these files). OBSPACK-Europe happens to be the last one listed, but I don't think this behaviour can be relied upon.

I reckon you can get at the information we want to filter on using: `dobj.info["specification"]["project"]["self"]["label"]`. But I am nowhere near confident enough to implement a fix based on this, and most likely there is a neater way (possibly inbuilt in the icoscp package, although I couldn't find it).

### Minimal Complete Verifiable Example

```Python
from openghg.retrieve.icos import retrieve_atmospheric
wao_data = retrieve_atmospheric(site="WAO", species="ch4")
wao_data.data
```

### Environment

Python 3.8.8
Openghg - devel commit: ec166689ab080b0458428aaee4c2102e37135fc7

**Comment by rt17603** [comment]
@ag12733 - Something to be aware of.

**Comment by gareth-j** [comment]
I'm working on this now.
