### ISSUE TITLE
Allow users to access data from a group object store and a local one

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#496]
We need to allow users to be able to access data from multiple object stores at once - their own local one and a group object store. This also means that it needs to be easy to change and work out which object store is being written to when adding data.

This may supercede Issue #262.

**Comment by rt17603** [comment]
Need to set up a meeting to discuss this and make sure we understand the underlying requirements.

**Comment by rt17603** [comment]
Links to PR #555 
Key summary from meeting:
 - Multiple object stores should be flat (no "precedence" between them)
 - Add ability to specify which object store to add to, search and to retrieve from
 - Allow searching all object stores (can return multiple SearchResults objects)
 - Allow retrieving from all object stores, *as long as there is no ambiguity* otherwise fail
 - Allow read/write equally from/to all object stores for now (consider read-only object stores in future)

**Comment by gareth-j** [comment]
I'm working on this now.
