### ISSUE TITLE
KeyError data lookup in Tutorial

### ISSUE THREAD

**Issue by ag12733** [openghg/openghg#506]
### Feature that's missing

Ran:

from openghg.standardise import standardise_surface

decc_results = standardise_surface(filepaths=tac_data, source_format="CRDS", site="TAC", network="DECC", overwrite=True)

Error:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[26], line 3
      1 from openghg.standardise import standardise_surface
----> 3 decc_results = standardise_surface(filepaths=tac_data, source_format="CRDS", site="TAC", network="DECC", overwrite=True)

File ~/Python/openghg/openghg/standardise/_standardise.py:113, in standardise_surface(filepaths, source_format, site, network, inlet, instrument, sampling_period, calibration_scale, overwrite)
    110 else:
    111     from openghg.store import ObsSurface
--> 113     results = ObsSurface.read_file(
    114         filepath=filepaths,
    115         source_format=source_format,
    116         site=site,
    117         network=network,
    118         instrument=instrument,
    119         sampling_period=sampling_period,
    120         inlet=inlet,
    121         overwrite=overwrite,
    122     )
    124     return results

File ~/Python/openghg/openghg/store/_obssurface.py:296, in ObsSurface.read_file(filepath, source_format, network, site, inlet, height, instrument, sampling_period, calibration_scale, measurement_type, overwrite, verify_site_code)
    294 # Create Datasources, save them to the object store and get their UUIDs
    295 data_type = "surface"
--> 296 datasource_uuids = assign_data(
    297     data_dict=data,
    298     lookup_results=lookup_results,
    299     overwrite=overwrite,
    300     data_type=data_type,
    301 )
    303 results["processed"][data_filepath.name] = datasource_uuids
    305 # Record the Datasources we've created / appended to

File ~/Python/openghg/openghg/store/_segment.py:49, in assign_data(data_dict, lookup_results, overwrite, data_type)
     46     datasource = Datasource.load(uuid=uuid)
     48 # Add the dataframe to the datasource
---> 49 datasource.add_data(metadata=metadata, data=data, overwrite=overwrite, data_type=data_type)
     50 # Save Datasource to object store
     51 datasource.save()

File ~/Python/openghg/openghg/store/base/_datasource.py:104, in Datasource.add_data(self, metadata, data, data_type, overwrite)
    101 self.add_metadata(metadata=metadata)
    103 if "time" in data.coords:
--> 104     return self.add_timed_data(data=data, data_type=data_type)
    105 else:
    106     raise NotImplementedError()

File ~/Python/openghg/openghg/store/base/_datasource.py:157, in Datasource.add_timed_data(self, data, data_type)
    155 combined_datasets = {}
    156 for existing_daterange, new_daterange in overlapping:
--> 157     ex = self._data.pop(existing_daterange)
    158     new = new_data.pop(new_daterange)
    160     print("NOTE: Combining overlapping data dateranges")

KeyError: '2012-07-26-11:23:05+00:00_2013-01-01-00:42:05+00:00'

**Comment by ag12733** [comment]
Tutorial store at time of error
Note: file was tarred but changed to .zip to allow upload here

[tutorial_issue_506.zip](https://github.com/openghg/openghg/files/10217085/tutorial_issue_506.zip)

**Comment by rt17603** [comment]
This could be related / impacted by Issue #465 - will see if this issue can be reproduced after a fix is completed for the overwrite key.

**Comment by rt17603** [comment]
The issue seems to be coming in when the "new" replacement data is being checked against "current" data for date overlap.

The way the date ranges have been split and defined (by year) is currently meaning multiple "new" date ranges are matching against the date ranges for the "current" data so when this is coming to remove and replace this data it deletes the relevant date range and then tries to delete this again.

The problem may relate to the period which is being used - this is currently set to 3600s (hourly) and the data may be on a different period e.g. 60s (minutely).

**Comment by gareth-j** [comment]
OK so I've kind of fixed this issue with a quick check to see if data is the same on adding in within Datasource. See [`_datasource.py:151`](https://github.com/openghg/openghg/blob/a533ca34eed70aaec04eee7ee35f9744bc366883/openghg/store/base/_datasource.py#L151)

```python
            if new_data == self._data:
                for _old, _new in zip(self._data.values(), new_data.values()):
                    if not _old.equals(_new):
                        break
                else:
                    logger.warning("No new data, nothing to do.")
                    return None
```

But this just bypasses the code that wasn't correct further below so we should rework that. This comes as part of the greater discussion we need to have about how we handle data that's updated and possible has bad data removed etc. I've created an issue for this #591.
