### ISSUE TITLE
from openghg.util import create_default_config fails

### ISSUE THREAD

**Issue by rebeccawardbristol** [openghg/openghg#507]
### Feature that's missing

Using vscode. Environment installed through pip. Config file was not created with import config. When trying from openghg.util import create_default_config this error arises:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[3], line 2
      1 import openghg
----> 2 from openghg.util import create_default_config

File ~/openghg/openghg/util/__init__.py:7
      5 from ._domain import convert_longitude, find_domain
      6 from ._download import download_data, parse_url_filename
----> 7 from ._export import to_dashboard, to_dashboard_mobile
      8 from ._file import (
      9     compress,
     10     compress_json,
   (...)
     23     read_header,
     24 )
     25 from ._hashing import hash_bytes, hash_file, hash_retrieved_data, hash_string

File ~/openghg/openghg/util/_export.py:6
      3 from typing import Dict, List, Union
      5 from addict import Dict as aDict
----> 6 from openghg.dataobjects import ObsData
      8 __all__ = ["to_dashboard", "to_dashboard_mobile"]
     11 def to_dashboard(
     12     data: Union[ObsData, List[ObsData]],
...
----> 8 from openghg.util import to_lowercase
     10 __all__ = ["BaseStore"]
     12 T = TypeVar("T", bound="BaseStore")

ImportError: cannot import name 'to_lowercase' from partially initialized module 'openghg.util' (most likely due to a circular import) (/user/home/ky20893/openghg/openghg/util/__init__.py)

**Comment by gareth-j** [comment]
Closing due this being an old version of openghg.

**Comment by rebeccawardbristol** [comment]
New error after update to devel:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[2], line 2
      1 import openghg
----> 2 from openghg.util import create_default_config

File ~/openghg/openghg/util/__init__.py:7
      5 from ._domain import convert_longitude, find_domain
      6 from ._download import download_data, parse_url_filename
----> 7 from ._export import to_dashboard, to_dashboard_mobile
      8 from ._file import (
      9     compress,
     10     compress_json,
   (...)
     23     read_header,
     24 )
     25 from ._hashing import hash_bytes, hash_file, hash_retrieved_data, hash_string

File ~/openghg/openghg/util/_export.py:6
      3 from typing import Dict, List, Union, Optional
      5 from addict import Dict as aDict
----> 6 from openghg.dataobjects import ObsData
      8 __all__ = ["to_dashboard", "to_dashboard_mobile"]
     11 def to_dashboard(
     12     data: Union[ObsData, List[ObsData]],
...
----> 6 from openghg.util import create_frequency_str, parse_period, relative_time_offset, timestamp_tzaware
      7 from pandas import DateOffset, Timedelta, Timestamp
      8 from xarray import DataArray

ImportError: cannot import name 'create_frequency_str' from partially initialized module 'openghg.util' (most likely due to a circular import) (/user/home/ky20893/openghg/openghg/util/__init__.py)

**Comment by rebeccawardbristol** [comment]
File ~/openghg/openghg/util/_export.py:6
      3 from typing import Dict, List, Union, Optional
      5 from addict import Dict as aDict
----> 6 from openghg.dataobjects import ObsData
      8 __all__ = ["to_dashboard", "to_dashboard_mobile"]
     11 def to_dashboard(
     12     data: Union[ObsData, List[ObsData]],
...
----> 1 from openghg.util import running_locally
      3 cloud_env = not running_locally()
      5 if cloud_env:

ImportError: cannot import name 'running_locally' from partially initialized module 'openghg.util' (most likely due to a circular import) (/user/home/ky20893/openghg/openghg/util/__init__.py)

**Comment by gareth-j** [comment]
This was due to an issue with the `openghg` confusing matters.
