### ISSUE TITLE
Consolidate (and remove) local site details in openghg

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#534]
### What is your issue?

Even after `site_info.json` will be split out into a separate repository (PR #519 ), there is still some site information stored and used within openghg. This should be reviewed and references to local site data should be kept to a minimum (or outsourced / removed if possible).

This includes (at least):
 - `site_lookup.json`
    - this is used by the `openghg.util.verify_site()` function

**Comment by gareth-j** [comment]
This should be closed by #537
