### ISSUE TITLE
Feedback on tutorials

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#547]
### What is your issue?

Feedback from Matt Rigby:

> Here are some suggestions:
> 
> Adding observation data:
> - [x] @SutarPrasad Explain what the object store is and why we use it. Explain difference between tutorial store and personal object store - add to top of https://docs.openghg.org/tutorials/local/Adding_new_data/Adding_observation_data.html
> - Perhaps this should be on a separate page explaining the OpenGHG architecture. - new issue #839
>
> - ~Section 1: Say that new data types can be added, as needed (link to instructions on how to do it)~ covered in #351 
> - [x] @brendan-m-murphy Section 1: Change format of summary outputs to focus on source rather than sites? Include narrative on what each datasource does (perhaps from docstrings??) - adding block to show how to see all details for one source_format - fixed with PR #841 
> - Section 1: We should change the tutorial workflow to first standardise something more general like ICOS/NOAA. The two examples given (DECC/AGAGE) are internal formats that only we have access to, so won't be particularly appealing to outsiders. - new issue #840
> - [x] Section 4: Make it clear that get_obs_surface is a wrapper for retrieve, etc. (since we've just talked about search and retrieve)?
>  
> Comparing observations to emissions:
> - [x] @rt17603 Need to clarify that this is a specific LPDM setup particular to our group, as in, e.g., Lunt 2016
>  
> Working with CO2:
> - [x] Some latex not rendered $\mathrm{CO_2}$

Feedback from Alice Ramsden:

> I’ve finished going through the ‘Modifying and deleting data’ notebook. I liked the detailed explanations for each step in that tutorial, it should be a useful tutorial to come back to when needed.
> 
> A couple of points to add/questions that could be used to expand the tutorial:
> - [x] @gareth-j Is the backup of the DataHandler object retained in the object store? Or is this a short term backup that is only linked to the recently created DataHandler object? Will this backup be overwritten if newer versions of the data objects are uploaded to the object store? 
> - [x] @gareth-j Is there a way to update the metadata of objects in bulk or does this have to be done manually by looping through all UUIDs? E.g. if you wanted to rename the ‘model’ for all footprints from all sites.

**Comment by chryswoods** [comment]
This will be folded into the release process - all of the tutorials will be run through by everyone to make sure that they make sense and they work with the 0.7.0 code.

Maybe do a scan through all of the documentation earlier. Possibly have a December early Christmas documentation day.
