### ISSUE TITLE
Distinguish between "levels" of data release

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#551]
### Is your feature request related to a problem?

At the moment, in addition to versions of a data file, there can be several functional levels of data depending on the stages in the processing.

This could include:
 - "raw" data with no calibration applied (NRT?)
 - partially finalised data but not fully signed off (or would this be closer to NRT?)
 - public access data from e.g. CEDA repository (QA/QC?)

This data will need to be distinguished and sometimes compared.

c.f. ICOS data level

### Describe the solution you'd like

Some way to distinguish between these different "data levels" using the metadata e.g. add `data_level` key or otherwise to observation metadata.

Features needed:
- This will need to be decided in some way in advance (e.g. 2 = public facing data, 1 = local processing)
- Could allow for flexibility (e.g. 1.1, 1.2, 1.3 etc. or could this be covered by existing versioning?)
- Can be related to where the data originates OR an input e.g. 2 = from external resource / matches to data level on that platform.
- Can tie into ranking where data level could be used as a distinguisher to specify a preference between "degenerate" data

**Comment by joe-pitt** [comment]
I like the idea of flexibility. It probably makes sense to keep the "L1" and "L2" definitions the same as ICOS. So having the ability to specify sublevels (e.g. L1.1, L1.2) could help with this? Then all L2 data could match a publicly-accessible data repository (and specify the source in the metadata?).

**Comment by rt17603** [comment]
@joe-pitt I suppose the main benefit of the "sub-levels" would be to allow easy comparison between pre-finalised versions of the data? Is that the use case you would have in mind for this?

**Comment by joe-pitt** [comment]
Yes - to allow comparison, and also to allow the NRT data to be L1, the final archived data to be L2, and the partially-finalised data to have some level in between. From a pure openghg perspective, it generally seems useful to allow for this flexibility in level naming (i.e. level numbers don't have to be integers). Then in the "acrg implementation" of openghg (i.e. the object store that we maintain on BP1) we can decide exactly how we want to define each sub-level (but in principle another group could maintain a local object store and define different sub-levels).

**Comment by rt17603** [comment]
Great, that makes sense. We could either do this (A) as proposed above with non-integer levels in some way or (B) have an additional label (e.g. `data_sub_level`). Either way this could be an extra way to distinguish which can be set by the data owners.

Another question around this is if we would want a search for "L1" to return ALL data labelled with L1 (even if this has a sub-level) OR only the data labelled as "L1" with no sub-level.

**Comment by joe-pitt** [comment]
Yeah good point - an additional data_sub_level label works just as well. It could potentially help to clarify things too - especially if there was a comment associated with each data_sub_level explaining what it refers to. I guess in that case it would make sense for a search of level=L1 to return all the sublevels? But I don't have a strong view on this - people with more end-user experience are probably better able to see the different pros/cons

**Comment by rt17603** [comment]
For OpenGHG
 - Can add new options: "data level", "data sub level" - check alignment with ICOS Carbon Portal
    - also "data sub level comment" - or something less cumbersome - Joe: something to help describe what is in the sub level
    - sub level can also be highly flexible as needed (could be numeric or otherwise)
    - level should be more strict - has to be an integer, >=0
 - Need to consider how this ties into ranking for both us and for the general product (ADVANCED)
    - Do we want this to be completely empty or could this be shipped with a few basic rules? Could allow these rules to be set up by choice?
      - Using command line interface could be good. E.g. $ openghg --setup-ranking
	     - Could present each basic rule and ask if user wants this to be included?
             - Use highest height when there is choice?
	     - Use highest level when there is a choice?
	     - Would need to include "highest" keyword and set up in some way.

**Comment by rt17603** [comment]
From Architecture planning meeting on 07/09/2023. Still add `data_level` but rather than adding a `data_sublevel` keyword could use the versioning for this, moving to the following.

Planning 

-  Initial Step: Add ‘data_level’ as a general key for all objects 
-  Next phase: Change how versioning is detailed 
    - Include details of versions within the metastore 
        - Full UUID becomes uuid/version e.g. 4d5-63u-rr3/v1 
        - Could split this out to be within a version column (just numerical) 
        - [Longer term could de-normalise – linking to an entry per datasource containing all the versions] 
    - Need to add layer within searching to group together details linked to the same Datasource and return the latest version  
        - Group on everything except specific version and version related details. 
        - Allow search for specific versions. 
        - “version” becomes special essentially 
- Can also include version specific metadata 
    - “label” / “comment” as a free form text input for each added piece of data – this can be different per version and added by the user 
    - “date” / “timestamp” for when the data was added to the object store. This would be automatically generated. 
- Consider how to make sure this is not a breaking change – need to ensure backwards compatability e.g. don’t worry about entries in the metastore with no version entry for instance and check there’s only one entry.

**Comment by joe-pitt** [comment]
Can I check I've understood - now the version number will replace the data_sublevel? One of my use cases is the AGAGE data, where we have L1 data (NRT), L2 data (from the archive), and also some data that is halfway between. This data has been checked by station operators and has been through the European data review process, but has not yet been signed off for release by the wider AGAGE group. It is this data that Alistair uses in his annual report/NIR inversions. I had in mind that I would call this something like: data_level=1, data_sublevel=Euro_QC. Now should I use: data_level=1, version=Euro_QC?

**Comment by brendan-m-murphy** [comment]
I think the idea is that if data at level X is updated, it is a new version, but it is still level X. If you want to add data at level X+1, it is a new "datasource", starting at version 0, and the data at level X is unaffected.

So maybe we need L0 (NRT), L1 (some checks, not signed off), and L2 (signed off for release). (Or L1, L1.5, L2 if NRT must be L1.)

For versions, I think the plan was, for each level, start the version numbers at 0 and just use the next whole number when a version is added. This made sense to us for cases when a new version was just a minor correction to the data. It sounds like NRT and Euro_QC should be different levels. (So if you decide to update the data after it has had some checks, but it is still not ready to be L2, then it would be a new version of the Euro_QC level.)

I think with Rachel's versioning updates, you can decide if a new version will replace the old version, or if both versions will be kept. Although for observations, it might be worth it to just keep most copies, since the data is small. (Then if the data is updated after someone has used it for an inversion, we would know exactly what data they used.)

We also discussed adding an option to include a message when data is updated. So you could have L1 include NRT and Euro_QC, and mention in the comment that the new version added is Euro_QC. I don't think we planned to make the comments searchable, but the default behaviour would be to return the latest version, so once NRT is updated to Euro QC as a new version, the Euro QC would be returned by default.

Does that make sense/seem like it would work for you?

**Comment by rt17603** [comment]
> Can I check I've understood - now the version number will replace the data_sublevel? One of my use cases is the AGAGE data, where we have L1 data (NRT), L2 data (from the archive), and also some data that is halfway between. This data has been checked by station operators and has been through the European data review process, but has not yet been signed off for release by the wider AGAGE group. It is this data that Alistair uses in his annual report/NIR inversions. I had in mind that I would call this something like: data_level=1, data_sublevel=Euro_QC. Now should I use: data_level=1, version=Euro_QC?

Happy to set up a chat about this so we can make sure this doesn't move too far away from what you were thinking (or just stick with the previously discussed plan)? The idea of folding this into the versioning was so this didn't create additional work for you when adding new data (i.e. you always have to label if) but if it isn't mapping to what would work practically then we can re-tool it.

**Comment by joe-pitt** [comment]
Ok cool - yeah essentially what I want is the freedom to set arbitrary levels. When we discussed this before, I think the following thoughts came up:

1) It would be nice to stick to the ICOS convention for data levels (NRT=1, final archive=2)
2) Having non-integer data levels might be confusing
3) Therefore to accommodate arbitrary levels (like my Euro_QC) we would have a data_sublevel

I'm not too concerned about non-integer data levels - it might have been @mrghg who made this suggestion? Either allowing flexibility in the data levels or having a sublevel would be fine by me.

**Comment by rt17603** [comment]
Comment on the current "icos_data_level" key, is that we need to consider how this relates to the more generic `data_level` key.

Suggestion for this would be:
 - retire `icos_data_level` and just use `data_level` instead. When pulling from ICOS what was `icos_data_level` would be used for `data_level` instead but could also be set in other circumstances as well.

Would there be any reason *not* to do this?

We need to consider and ensure this still works well enough with a current object store which already used `icos_data_level`.

**Comment by joe-pitt** [comment]
Retiring icos_data_level sounds fine to me

**Comment by rt17603** [comment]
> Comment on the current "icos_data_level" key is that we need to consider how this relates to the more generic `data_level` key.
> 
> Suggestion for this would be:
> 
>     * retire `icos_data_level` and just use `data_level` instead. When pulling from ICOS what was `icos_data_level` would be used for `data_level` instead but could also be set in other circumstances as well.
> 
> 
> Would there be any reason _not_ to do this?
> 
> We need to consider and ensure this still works well enough with a current object store which already used `icos_data_level`.

New issue created for this - #1067

**Comment by rt17603** [comment]
Keys have now been added.
