### ISSUE TITLE
BoundaryConditions metadata incorrect / type coercion error

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#575]
So we're getting values that we probably don't want in our boundary conditions metadata.
We should have a look at what we want to store for things like resolution and lat/long values.

```
cams_resolution': "<xarray.dataarray 'latitude' ()>\narray(0., dtype=float32) 
x <xarray.dataarray 'longitude' ()>\narray(0., dtype=float32)",
```

**Comment by SutarPrasad** [comment]
Can't recreate the problem
