### ISSUE TITLE
Why is `long_name` not in the attributes - Macehead and Cabauw

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#592]
When processing GCWERKS data for Macehead and some data for Cabauw the `long_name` attribute isn't being added to the Dataset. Need to look into why this isn't happening.

**Comment by gareth-j** [comment]
So this was  due to read the attribute from the wrong place, it should be reading from the `data[species].attrs["long_name"]` not `data.attrs["long_name"]`.

**Comment by rt17603** [comment]
@gareth-j - was this something that needed fixing then? Or could this be closed?

**Comment by gareth-j** [comment]
This can be closed.
