### ISSUE TITLE
ICOS retrieve error - found via doc build

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#598]
So I just encountered this error whilst building the docs, in `Retrieving_remote_data.rst` we use the `ipython::` Sphinx directive which runs the lines as it goes. I get this error which looks like somethings changed since we outsourced the metadata maybe?

```python
File ~/Documents/Devel/openghg/openghg/standardise/meta/_metadata.py:84, in sync_surface_metadata(metadata, attributes, keys_to_add, update_mismatch)
     82 if str(value).lower() != str(attr_value).lower():
     83     if not update_mismatch:
---> 84         raise AttrMismatchError(
     85             f"Metadata mismatch for '{key}', metadata: {value} - attributes: {attr_value}"
     86         )
     87     else:
     88         logger.warning(
     89             f"Metadata mismatch for '{key}', metadata: {value} - attributes: {attr_value}\n"
     90             f"Updating metadata to use attribute value of {key} = {attr_value}"
     91         )

AttrMismatchError: Metadata mismatch for 'station_long_name', metadata: WAO - attributes: Weybourne Observatory, UK
```

**Comment by rt17603** [comment]
I'd say this is part of a larger conversation we keep coming back to about how we want to handle these mismatches. From discussion on the code retreat Alice opened up Issue #613 for discussion around this as well.

**Comment by gareth-j** [comment]
This no longer happens as the site has been changed to SCO.
