### ISSUE TITLE
Mismatch inlet error for some standard input files

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#60]
Inlet mismatch when reading in some files from Shangdianzi, Ridgehill, Tacolneston and Cape Grim. These should be standard files for these sites and so inlets should match with whats being checked against. Apart from the files other inputs supplied to read the file were the "data_type", "site" and "network". 

```
Traceback (most recent call last):
  File "/home/rt17603/openghg/openghg/modules/_obs_surface.py", line 132, in read_file
    measurement_type=measurement_type
  File "/home/rt17603/openghg/openghg/modules/_gcwerks.py", line 116, in read_file
    data_filepath=data_filepath, precision_filepath=precision_filepath, site=site, instrument=instrument, network=network
  File "/home/rt17603/openghg/openghg/modules/_gcwerks.py", line 246, in read_data
    scale=scale,
  File "/home/rt17603/openghg/openghg/modules/_gcwerks.py", line 331, in split_species
    "Inlet mismatch - please ensure correct site is selected."
ValueError: Inlet mismatch - please ensure correct site is selected.Mismatch between inlet in data and inlet in parameters file.
```

Details of all affected files and inputs to ObsSurface.read_file() function included here:
[file_input_errors_mismatch_inlet.txt](https://github.com/openghg/openghg/files/6366970/file_input_errors_mismatch_inlet.txt)

**Comment by rt17603** [comment]
May be for these sites that this is unable to infer the inlet from the data file? Need to think about how to streamline this if this is the case.

**Comment by mrghg** [comment]
If you take a look at the acrg repo, you'll see that there are various fudges to get sensible inlet labels. E.g. Cape Grim matches inlets based on a set of wildcards (something like "7*m*" > "70m", because there are a bunch of inlet labels called things like 70m_1, 75m_2, etc., which I've just assumed to be 70m). For SDZ, there was a change in the inlet height at some point, so my processing splits things by date (take a look at the "inlet_label" part of the gcwerks_params file). It's a real mess!

**Comment by rt17603** [comment]
Does this link to the PR #54 you were putting together? I think Gareth completed and merged that but maybe it needs a revisit?

**Comment by mrghg** [comment]
See also issue #45 and PR #54

**Comment by mrghg** [comment]
Guess we replied at the same time! Yeah, haven't had a chance to test Gareth's changes yet. Would be great if you could take a look.

**Comment by rt17603** [comment]
I raised this Issue today and PR #54 3 days ago, so I should be running against the devel version where this PR has been merged but can run again to check.

**Comment by rt17603** [comment]
Just pulled the latest version of devel and ran this again for "shangdianzi-medusa.10.C". I get the same error as above:

```
defaultdict(dict,
            {'error': {'shangdianzi-medusa.10.C': 'Traceback (most recent call last):\n  File "/home/rt17603/openghg/openghg/modules/_obs_surface.py", line 132, in read_file\n    measurement_type=measurement_type\n  File "/home/rt17603/openghg/openghg/modules/_gcwerks.py", line 116, in read_file\n    data_filepath=data_filepath, precision_filepath=precision_filepath, site=site, instrument=instrument, network=network\n  File "/home/rt17603/openghg/openghg/modules/_gcwerks.py", line 246, in read_data\n    scale=scale,\n  File "/home/rt17603/openghg/openghg/modules/_gcwerks.py", line 331, in split_species\n    "Inlet mismatch - please ensure correct site is selected."\nValueError: Inlet mismatch - please ensure correct site is selected.Mismatch between inlet in data and inlet in parameters file.\n'}})
```

**Comment by rt17603** [comment]
More detail on input files with this error:
1. 'shangdianzi-medusa.10.C' [ and other files]
- Inlet set to "ASM" e.g.
       Year  yyyy mm dd  hh mi  ryyy rm rd  rh ri         Inlet     
2010.335679  2010 05 03  12 33  2010 05 03  12 33           ASM 
...

2. & 3. 'capegrim-gcms.97.C' ; 'tacolneston-md.11.C'
- Inlet set to "-" e.g.
       Year  yyyy mm dd  hh mi  ryyy rm rd  rh ri         Inlet     
1997.841640  1997 11 04  04 46  1997 11 04  05 06             -     

4. 'ridgehill-md.11.C'
- Inlet set to "window" e.g.
       Year  yyyy mm dd  hh mi  ryyy rm rd  rh ri         Inlet     
2011.919005  2011 12 02  10 29  2011 12 02  10 29        window
