### ISSUE TITLE
Add pytest to environment.yaml

### ISSUE THREAD

**Issue by joe-pitt** [openghg/openghg#610]
### What is your issue?

Unless I'm going mad, pytest isn't currently in the environment.yaml file so it must be installed separately. Maybe this is deliberate for some reason, but if not it would be nice to add it to save a few seconds of time.

**Comment by mrghg** [comment]
I guess we should have a dev environment file, like requirements-dev. Should also include pytest-mock and other dev libraries

**Comment by SutarPrasad** [comment]
- [ ]  This issue will be closed under #769
