### ISSUE TITLE
Allow information mismatches to be updated by attribute (internal) data or metadata (external)

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#638]
## What is your issue?

When there is a mismatch between metadata in the openghg supplementary data files and between attributes in a data file, the data file cannot be added to an object store. PR #625 will aim to allow this to happen by using the attribute values by default.

To add flexibility for cases where the external parameter data (metadata e.g. from site info, openghg files, parameters passed by the user) should be used in preference to the internal parameter data (attributes e.g. parameters which came with the file), this should allow for different options including:
 - "never" - don't update mismatches (supported by update_mismatch=False in PR #625)
 - "attributes" / "internal" / "from_source" - update mismatches based on internal data (supported by update_mismatch=True in PR #625 )
 - "metadata" / "external" / "from_definition" - update mismatches based on external data (NEW)

In cases where the mismatches are updated, the code should update either the metadata OR the attributes and print out a warning about which source of information has been used.

This builds on #613

**Comment by rt17603** [comment]
It may help to try and untangle what we mean by attributes and metadata initially to help distinguish the sources of information and when one may be more useful than the other. By linking these two terminologies to sources of data this may make resolving mismatches make more sense.

I propose the following distinction at input:

    metadata (or external?) - any parameters defined external to the data. This includes:
        supplementary data repo (site and species info)
        additional "internal" to openghg files (attributes.json, ...)
        values passed in by the user (e.g. to the standardise functions such as known arguments or kwargs)
    attributes (or internal?) - any parameters than come from / with the data itself
        for GCWERKS, CRDS etc. this may mean these essentially have NO attributes and all the values included for them are from the "metadata" as we have defined above.
        for ICOS, NOAA, pre-existing netcdf files (openghg format for example) these may have "attributes"

Loosely this could be described as:

    "attributes" (or internal?) already exist and are associated with the data
    "metadata" (or external?) for the data is created from additional sources

At this point, we then have two sources of information which we need to use to create our stored object and label our data. For the attributes and metadata output we store in the object store, this can link to the workflow principles:

    The metadata should be compiled in a relatively consistent way between parsing functions.
    Attributes come from the data. These may need to be compiled depending on the source but should be kept as close to the original as reasonable.
        There are known corner cases for this e.g. NOAA data sources contain lots of details and we may not want to keep all of them. ICOS associated data comes from different sources (data details, station details) but all within the data returned.
    Matching keys within attributes and metadata must be compared before being stored
        If any don't match we either raise an error or choose how to synchronise them
    Attributes can be used to create missing metadata and vice versa
        What counts as missing data needs to be determined in advance (e.g. via a function definition)
    If the previous statement is true, the attributes and metadata don't need to interact before the point of synchronisation.
        In fact, maybe this should be enforced to keep these two sources of information distinct
    As long as overlapping keys do match, attributes and metadata don't have to be identical as they serve different purposes (one is stored within the data and makes outputting to file simpler, the other is used for categorising the data within the object store).

Most of these principles are already been adhered to but this may need to be folded through in a consistent way.

**Comment by rt17603** [comment]
Maybe terminology around "internal", "external" for input sources rather than "attributes", "metadata" may be better for clarity (could still use "attributes", "metadata" for output).

**Comment by rt17603** [comment]
> I think I follow this, and it sounds like a good plan! Internal/external seems like a more logical nomenclature than attributes/metadata to me. Just to make sure I am with this - under the proposed new system, if I set update_mismatch="external", would the station_long_name be taken from the file on the ICOS Carbon Portal (e.g. Line 9: "# STATION NAME: Gartow") rather than site_info.json?

@joe-pitt . So for the ICOS case described it would actually be the opposite - "internal" would refer to the attributes which came with the download (i.e. the data from the ICOS Carbon portal) and "external" would refer to the values stored externally in this case our site_info.json. So update_mismatch="external" this would use the data from site_info.json and update_mismatch="internal" would use the data from the ICOS carbon portal.

By "internal" I was thinking this is details explicitly linked to the data (in this case downloaded with the data); "external" were details defined externally to the data. Sounds like that may be a bit confusing though - so tell me if you think there's a more logical way to describe this.

**Comment by joe-pitt** [comment]
Aha I see - internal to the original file, rather than internal to our json. That does make sense, but the fact I assumed this was the other way round initially perhaps suggests it isn't foolproof. Maybe it could be as explicit as update_mismatch="from_original_file" and update_mismatch="from_json"? Unless there are other cases not covered by this wording that I haven't thought of?

**Comment by rt17603** [comment]
Good idea - instead of "internal" perhaps "from_original_file" or "from_data" or "from_source" some variant as per your suggestion.

For "external", as well as site_info.json, I was initially thinking this could also include any additional keywords passed by the user and other attribute files (e.g. we have the "attributes.json" file still used for some AGAGE data) - I don't want to split this out even further at this point but not initially sure what other terminology could be used to link them together? Maybe something like "from_definition"? Still not very clear could we can include details in the documentation.
