### ISSUE TITLE
Tidy processing status bar - use `rich`?

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#639]
We should tidy the file processing progress bars to use something like `rich` and update the progress in place instead of printing a hundred lines to screen. For example when we run `add_noaa_obspack` we get lots of lines being printed whereas we could just have a nice single progress bar.

**Comment by SutarPrasad** [comment]
How about using tqdm.rich instead of removing entire package?

**Comment by gareth-j** [comment]
I think we should just move wholesale to rich, it comes with quite a few features that we can take advantage of other than just the progress bars.

**Comment by gareth-j** [comment]
Closing this as we've got more discussion on #686
