### ISSUE TITLE
Decide how to handle data for the same base keyword combination (e.g. site/species/height) from different sources (e.g. NRT, ObsPack)

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#654]
### What is your issue?

We need to decide how to further sub-categorise data associated with the same set of nominal keywords from different sources.

For example: we will have data from Mace Head (same species and inlet) which may be continuous Near Real time, from an ObsPack, from the ICOS Carbon Portal.

Suggestions include:
 - ~~a `source` field~~ a `dataset_source` field - could be relatively free form but with suggested consistency for known values such as "noaa_obspack", "icos_portal", "raw_data" (keeping lower case for now for consistency with other metadata)
     - *From feedback - the `dataset_source` field is already included as an option within the `retrieve_atmospheric` input. We can determine how this can be folded back throughout in a more generic way for other source formats and `standardise_surface` input keywords.*
 - a `label` field - potentially completely free-form (could be more verbose) e.g. "noaa obspack L2 data"

Note that some of this has already been discussed and covered regarding data level (L1, L2 classification) #551  and a `data_level` (and `data_sub_level`) keyword will also be made available independently of this.

Also c.f. discussion on internal versioning which tracks the history of a specific DataSource #597

**Comment by joe-pitt** [comment]
I'm a bit confused as to how these will be different from the data_source and dataset_source attributes that we already have?

**Comment by rt17603** [comment]
For reference `data_source` at the moment links to where the data was retrieved from and is only used for the `retrieve_atmospheric` via `local_retrieve` and is set to `"icoscp"`.

**Comment by rt17603** [comment]
From discussion on 05/06/2023:

- Can make sure `dataset_source` is available as a general keyword when adding new data (`standardise_surface` at least). In addition to current values of "InGOS" or "European ObsPack" this could include e.g. "CEDA 2023.06" in relation to CEDA versioning.
    - This keyword can be optional and so would not always need to be included. In the case where new data is added that doesn't come from multiple dataset sources, this can be omitted (if new data were to be added later which *does* need a distinction, it would be possible to update the metadata on the previous data).
- `data_source` links to where the data was retrieved from and is also useful but could be renamed to `retrieved_from` e.g. "icoscp", "ceda". For internal processing we could either include "internal" or just omit this.

Other points:
- Suggest that if identifying metadata can be included which distinguishes between different data sets this is used (in preference to relying on versioning)
    - If a priority needs to be included for the data, the Ranking can be included for this
- For versions of the same data (all identifying metadata is the same for all versions), this can be used as a way to track the history of the file and should be made more accessible.
    - Could also add a label and/or comment associated with versions for a single Datasource
