### ISSUE TITLE
Update activation command for virtual environment

### ISSUE THREAD

**Issue by Devazc** [openghg/openghg#673]
### What is your issue?

Hello,

I encountered an issue while trying to activate the virtual environment using the command `source openghg_env/bin/activate` as mentioned in the documentation. However, on my Windows system using both Command Prompt and Git Bash, this command did not work.

After some investigation, I found that using the command `source openghg_env/Scripts/activate` in Git Bash successfully activated the virtual environment.

Thank You !

**Comment by gareth-j** [comment]
We don't support Windows at the moment so closing this.
