### ISSUE TITLE
Unable to add MHD footprints to shared object store - potentially issue with memory usage

### ISSUE THREAD

**Issue by aliceramsden** [openghg/openghg#676]
### What is your issue?

I'm unable to add any MHD footprints to the shared object store (`/group/chemistry/acrg/ES_store/openghg_store`), potentially because of an issue with memory usage.

When I try to run the `standardise_footprint()` function in a Jupyter notebook, the function just hangs indefinitely.
When I run the same function in a script on the BP1 compute nodes, the run fails out even when I set the memory to 60GB.

I haven't had any issues when adding any other footprints from other sites to this object store (and these scripts have run correctly on the compute nodes when setting the memory allocation to 10GB) so it must be something to do with these MHD files.

Here's an example footprint month that doesn't work for me, but I'm unable to add any MHD files from any dates:
`standardise_footprint(filepath='/group/chemistry/acrg/LPDM/fp_NAME/EUROPE/MHD-10magl_UKV_EUROPE_202102.nc',
site='MHD',height='10magl',domain='EUROPE',model='NAME',metmodel='UKV',overwrite=False)`

**Comment by gareth-j** [comment]
This looks like something that could maybe be fixed using a caching
strategy similar to the method we used in the name_processing repo.

**Comment by aliceramsden** [comment]
I've followed this issue through to where the actual problem is occuring:

`standardise/_standardise.py` line 275: `Footprints.read_file()`
`store/_footprints.py` line 384: `assign_data()`
`store/_segment.py` line 46:` Datasource.load()`

The Datasource.load() line just hangs until it runs out of memory.

Line 41 in `_segment.py` says:
        
# If we have a UUID for this Datasource load the existing object
# from the object store

I'm not sure how the objectstore works behind the scenes, but does this mean that it reads in an object that already contains similar data (in this case MHD footprints) and then the new file is added to this?
If this is the case, could the issue be that the data that's aready associated with MHD footprints is either corrupt or too large to read in? So it's getting stuck at that point, before it tries to add the new data?

**Comment by rt17603** [comment]
Yes you're right that it'll look for an existing data source with the keywords supplied and load in any existing data it finds.

So we likely need to tread carefully and understand what data is present and why but in principle data which already exists in the object store can be deleted - [Modifying_and_deleting_data](https://docs.openghg.org/tutorials/local/Managing_object_store/Modifying_and_deleting_data.html)

**Comment by rt17603** [comment]
Depending on the data being added as well, it may also be that we're not using enough of the supplied keywords to categorise the footprint data. So we may need to put in a fix to distinguish using more keywords e.g. met_model etc.

Really we need to determine whether the data you're adding should be being grouped together with the data already stored.

**Comment by aliceramsden** [comment]
I've tried to add the same set of MHD footprint files (e.g. `'/group/chemistry/acrg/LPDM/fp_NAME/EUROPE/MHD-10magl_UKV_EUROPE_202102.nc'`) to a new empty object store and this has worked without any issues. `openghg.standardise.standardise_footprint()` adds the file to the new object store without any problem, and I can then retrieve the data as expected. 

So I think this confirms that the issue above is due to the current shared object store, or how these files in particular (MHD 2021 footprints) are interacting with the shared object store.

**Comment by rt17603** [comment]
> I've tried to add the same set of MHD footprint files (e.g. `'/group/chemistry/acrg/LPDM/fp_NAME/EUROPE/MHD-10magl_UKV_EUROPE_202102.nc'`) to a new empty object store and this has worked without any issues. `openghg.standardise.standardise_footprint()` adds the file to the new object store without any problem, and I can then retrieve the data as expected.
> 
> So I think this confirms that the issue above is due to the current shared object store, or how these files in particular (MHD 2021 footprints) are interacting with the shared object store.

Ok thanks for doing that Alice - one thing to note is that I am currently working on setting up a new object store which changes some of the ways the data is stored internally. Work on this is completed as part of a separate milestone - https://github.com/openghg/openghg/milestone/13 with the current updates on PR #680 . As a part of this it would really helpful if you could add the details of scripts/notebooks/files you're adding to the object store to https://github.com/ACRG-Bristol/populate that would make this smoother.

Having said all that, if there needs to be an update for the current object store then that's fine. Are you able to work around this at the moment or is this still a blocker?

**Comment by aliceramsden** [comment]
> > I've tried to add the same set of MHD footprint files (e.g. `'/group/chemistry/acrg/LPDM/fp_NAME/EUROPE/MHD-10magl_UKV_EUROPE_202102.nc'`) to a new empty object store and this has worked without any issues. `openghg.standardise.standardise_footprint()` adds the file to the new object store without any problem, and I can then retrieve the data as expected.
> > So I think this confirms that the issue above is due to the current shared object store, or how these files in particular (MHD 2021 footprints) are interacting with the shared object store.
> 
> Ok thanks for doing that Alice - one thing to note is that I am currently working on setting up a new object store which changes some of the ways the data is stored internally. Work on this is completed as part of a separate milestone - https://github.com/openghg/openghg/milestone/13 with the current updates on PR #680 . As a part of this it would really helpful if you could add the details of scripts/notebooks/files you're adding to the object store to https://github.com/ACRG-Bristol/populate as that would make this transition smoother.
> 
> Having said all that, if there needs to be an update for the current object store then that's fine. Are you able to work around this at the moment or is this still a blocker?

Ok, it sounds like that new object store setup could solve this issue then. For now, I can continue using my new separate object store for the PARIS work that needs completing soon. So this issue isn't a blocker for this anymore.

I don't think I've been adding anything notable to the shared object store (only footprints for 2021) and I've been using the populate functions already contained in that repository, but I can check through and see if there's anything missing.

**Comment by chryswoods** [comment]
The fix by @brendan-m-murphy in #513 may help with this.

A full fix will come with the special release #591.

**Comment by rt17603** [comment]
This should be addressed as part of #561 (and #867 , #908 ) and this will be closed when the overall `new_object_store` branch is merged into `devel` #831 .
