### ISSUE TITLE
rich package to replace tqdm progress bars

### ISSUE THREAD

**Issue by SutarPrasad** [openghg/openghg#686]
### What is your issue?

Hi As per the discussions in Issue https://github.com/openghg/openghg/issues/639 updating the code to utilise rich package.

**Comment by SutarPrasad** [comment]
The rich package extensively takes care of the various functionalities like customising CONSOLE output, adding highly user-friendly PROGRESS_BARS, and has its own LOGGERS. It seems to be highly useful for us to implement and have nice and user-friendly terminal outputs. 
However, while implementing the progress bar it has come to my notice that using a standard logger with a rich progress bar breaks the console outputs and the only solution is to either use progress.log() from "rich.progress.Progress" or else entirely updating the repositories logger to use "RichHandler()" and "rich-logger"

We can discuss if we want to exhaustively utilise the functionalities of the rich package and we can determine the step-by-step process of implementing it entirely or have a partial implementation.
 
Potentially opening separate issues to have better track of it.

**Comment by gareth-j** [comment]
I think there are still a couple of questions on that PR that need addressing, mainly around the removal of the progress bar from the ObsSurface processing.
