### ISSUE TITLE
Unable to apply average to data when using footprint_data_merge

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#69]
At the moment there is no way to apply an explicit average to the obs data timeseries when merging with the footprints. This can be done when creating the separate data object using the `get_obs_surface()` function but this is not called when using `footprint_data_merge()` as present.

This may link to Issue #42, as this may be something we incorporate into a new workflow rather than apply separately to the current code.

**Comment by gareth-j** [comment]
For the moment we could just add averaging until the work discussed in #42  is done?

**Comment by gareth-j** [comment]
Closing this due to the work being covered by #42 .
