### ISSUE TITLE
Ranking date range cannot be set to be open ended

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#72]
At present when setting a date range for the data ranking this must be specified as:

"startdate_enddate" e.g. "2012-01-01_2013-01-01"

For several sites, the range related to the ranking is open-ended. For instance at Tacolneston there is a change on "2013-01-01" from using data at inlet height 100m to 185m instead. When asking for dates before 2013-01-01, the higher ranked data is "100m" and on and after 2013-01-01 the higher ranked data is "185m".

One input suggestion would be to allow for a preceding or trailing underscore "_" to indicate an open ended date range for this:

`obs = ObsSurface.load()`
`obs.set_rank(uuid=uid_100, rank=1, date_range="_2013-01-01")`
`obs.set_rank(uuid=uid_185, rank=1, date_range="2013-01-01_")`

and perhaps extracting the start or end date from the data present if needed.

**Comment by gareth-j** [comment]
@rt17603 do we still need this open?
