### ISSUE TITLE
BTT module not integrated into ObsSurface options yet

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#73]
The module to process the BTT (BT Tower) data is not integrated into the ObsSurface options yet. BTT data type is not included within `DataTypes` class yet (defined in `openghg/processing/_enums.py`)

If this is added, the metadata output also seems like it would need to be updated to be more in line with expected ObsSurface checks - for example:

`btt_results = ObsSurface.read_file(filepath=filepath, data_type="BTT", site="BTT", network="LGHG")`

` File "/home/rt17603/openghg/openghg/modules/_obs_surface.py", line 148, in read_file`
`    lookup_results = obs.datasource_lookup(metadata=metadata)`

` File "/home/rt17603/openghg/openghg/modules/_obs_surface.py", line 181, in datasource_lookup`
`    site = data["site"]`

`KeyError: 'site'`

**Comment by gareth-j** [comment]
Need to add BTT to the list of accepted data types.

**Comment by gareth-j** [comment]
This was fixed.
