### ISSUE TITLE
Umbrella issue: short term solution for concurrency problem

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#765]
For the concurrent write (and potentially read) problem we can execute the following steps for a quicker fix on the path to a longer term solution (e.g. using MongoDB - #756 )

- [x] #762 - being addressed by #763
- [x] #695 
- [x] #764

**Comment by chryswoods** [comment]
@gareth-j will add in support for lock files after doing work on zarr. This will be via time-limited lock-files. It is noted that this is a short-term fix that will be resolved properly by the mongodb work #756 and zarr work in the special release.

This issue relates only to the short-term fix needed for 0.7.0.

This solution may benefit from a short technical meeting focussed around this topic.

**Comment by rt17603** [comment]
Closed with final PR #695

**Comment by rt17603** [comment]
Closed with final PR https://github.com/openghg/openghg/issues/695
