### ISSUE TITLE
`ModelScenario.calc_modelled_obs` throws an error if 'source' or 'sources' isn't specified

### ISSUE THREAD

**Issue by brendan-m-murphy** [openghg/openghg#786]
### What happened?

I created a model scenario with obs, footprint, flux, and bc data: 

`scenario = ModelScenario(site='tac', species='ch4', inlet='185m', domain='europe', start_date='2019-01-01')`

The model scenario was successfully created with all four data types:

```
INFO:openghg.analyse:Adding obs_surface to model scenario
INFO:openghg.analyse:Updating any inputs based on observation data
INFO:openghg.analyse:site: tac, species: ch4, inlet: 185m
INFO:openghg.analyse:Using height_name option(s) for footprint inlet: 185magl
WARNING:openghg.retrieve:No data found for the dates given in the user store, please try a wider search.
INFO:openghg.analyse:Adding footprint to model scenario
WARNING:openghg.retrieve:No data found for the dates given in the user store, please try a wider search.
INFO:openghg.analyse:Adding flux to model scenario
INFO:openghg.analyse:Adding boundary_conditions to model scenario
```

The attributes `scenario.obs, scenario.footprint, scenario.bc, scenario.fluxes` had the expected data.

However, `scenario.fluxes` used `None` as the key for the flux, since I didn't specify `source` or `sources` in `__init__`:

```
In [78]: scenario.fluxes
Out[78]: 
{None: FluxData(data=<xarray.Dataset>
 Dimensions:  (lat: 293, lon: 391, time: 1)
 Coordinates:
   * lat      (lat) float32 10.73 10.96 11.2 11.43 ... 78.36 78.59 78.82 79.06
   * lon      (lon) float32 -97.9 -97.55 -97.2 -96.84 ... 38.32 38.68 39.03 39.38
   * time     (time) datetime64[ns] 2019-01-01
   ...
```

This caused an error when I called `scenario.footprints_data_merge()`:

```
ModelScenario.combine_flux_sources(self, sources, cache, recalculate)
    841 time_dim = "time"
    843 sources = self._clean_sources_input(sources)
--> 844 sources_str = ", ".join(sources)
    846 # Return any matching cached data
    847 if self.flux_stacked is not None and not recalculate:

TypeError: sequence item 0: expected str instance, NoneType found
```

### What did you expect to happen?

I expected to get combined data back from the function call.

### Anything else we need to know?

The issue is on lines 817-818 of _scenario.py:

```
        if sources is None:
            sources = list(flux_dict.keys())
```

The variable `sources` is passed to `combine_flux_sources`, which tries to do `", ".join(sources)`.

### Environment

<details>
Python version 3.9
OpenGHG version 0.6.2

</details>

**Comment by rt17603** [comment]
At the moment this happens in the case where the search was able to find a unique flux without source / sources being specified 

So we could take this one of two ways:
 1. We could change that so it only adds a flux *if* source or sources is specified
 2. We could add a clause after the flux has been found to check *if* source / sources is None and then populate this from the metadata - I believe this is what you suggested already and I think this option is a good one (can decide to update to (1) instead later on if we decide this needs to be more strict)

**Comment by brendan-m-murphy** [comment]
At least for `combine_flux_sources`, the `sources_str` isn't very important, it's mostly just for caching I think.

If the source/sources can't be found in the source metadata, should there be a default string, or should we throw an error?

**Comment by rt17603** [comment]
The [`standardise_flux` function](https://github.com/openghg/openghg/blob/devel/openghg/standardise/_standardise.py#L452) should require `source` to be specified so it's reasonable to throw an error if this isn't found as something about the stored data itself is faulty.

Regardless, if a flux is associated with ModelScenario there should be a known source at the stage where it's added to the object.

**Comment by brendan-m-murphy** [comment]
Sorry I didn't see your comment until after I pushed a fix. I made "no_source_specified" the default key for `ModelScenario.fluxes` if only one flux is added but source/sources isn't specified, and the metadata doesn't have a 'source' key.

You're saying the last scenario can't happen? (Or should be an error if it does happen.)
