### ISSUE TITLE
Issue with deleting and re-adding ICOS data from object store (remnant of previous entry)

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#815]
From @joe-pitt on 03/11/2023
"OK so I deleted all the ICOS obs from paris_openghg_store and tried to repopulate it with updated data, but randomly some data from the 2018 drought paper crept in. I updated my populate script to exclude this random data, deleted all the icos data again, and tried to repopulate again. However now when I try to add the data I get the message:

WARNING:openghg.store:Note: There is no new data to process.

When I look in the store there is no icos data there. I guess there is still some remenant of the data in the store somehow - any suggestions on how to force an update using the current openghg?
"

**Comment by brendan-m-murphy** [comment]
I can confirm that there isn't any ICOS metadata in the ObsSurface metastore, but there are a lot of *retrieved* hashes in the metadata stored by the `ObsSurface` class when adding data to the object store.

So, whatever method was used to delete the data didn't clear the "retrieved hashes", which is why OpenGHG is saying the data has already been added.

@joe-pitt could you share the script you used, or describe the method you used to delete the data? It was successfully removed from the metastore, but not from the metadata that tracks what data has been added. (And actually, I see no reasonable way to decide how to remove these hashes unless the file hash is stored with some identifying info somewhere else.)

**Comment by joe-pitt** [comment]
I used the following:

```
dm_lookup = dataobjects.data_manager(data_type="surface",
                                     store=store,
                                     datasource="icoscp")
uuids = list(dm_lookup.metadata.keys())
dm_lookup.delete_datasource(uuid=uuids)

```

If there isn't a simple way to resolve this then don't worry - I can stick to using a separate store for these obs for now, and then update the Paris store once the new functionality for updating data gets implemented.

**Comment by brendan-m-murphy** [comment]
@rt17603 discussed this on Teams:

- In the near future, there will be a "force" option that ignores the stored hashes (part of the `new_object_store` branch)
- We should store some info connecting the hashes to the data sources:
    - some files will result in multiple datasources
    - multiple files can be added to the same datasource (for different time periods)
    - so, we need to associate to each file/retrieved hash the (list of) UUID(s) of the data source(s) the data was added to, as well as the time period that the data spans
    - we need to update data manager to remove hashes when a datasource is deleted

**Comment by brendan-m-murphy** [comment]
We're going to add a `force` option to ignore hashes when retrieving data from ICOS, NOAA, etc. as a short term fix.

We might need to open a new issue around improving what is stored with hashes.

**Comment by joe-pitt** [comment]
OK this all sounds good - thanks for looking into it! For now I will leave the obs in the separate object store that I created, then when I next come to update the obs I will try using the new force option. Shall I close this issue?

**Comment by brendan-m-murphy** [comment]
@joe-pitt that's okay, I'll close it when the PR goes through. Should be soon though.

**Comment by brendan-m-murphy** [comment]
@joe-pitt there is a fix for this now on the `devel` branch. If you pass `force=True` to `retrieve_atmospheric`, it will ignore existing file hashes.

**Comment by rt17603** [comment]
@brendan-m-murphy - I think the associated PR has been merged now - can this issue be closed?

**Comment by brendan-m-murphy** [comment]
@rt17603 I created another issue around improving how the hashes are linked to the stored data, which wasn't addressed in the PR
