### ISSUE TITLE
Add default sampling period for remaining modules (where appropriate)

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#84]
Including NOAA data.

Aim for default to all different data sources (needed input?)

**Comment by gareth-j** [comment]
We need to make a list of the data we have and what's missing.

**Comment by rt17603** [comment]
Default sampling period value not known: 
- AQMesh - sampling_period = "NA"
- Beaco2n - sampling_period = "NOT_SET" or set using an input
- Cranfield - sampling_period = "NOT_SET" or set using an input
- EUROCOM - sampling_period = "NOT_SET" or set using an input
- Glasgow_licor - no sampling_period set
- Glasgow_picarro - sampling_period = "NA" or set using input
- NOAA - sampling_period = "NOT_SET" or set using an input
- NPL - sampling_period = "NOT_SET" or set using an input
-  Thames Barrier - sampling_period = "NOT_SET" or set using an input

Sampling period default/value is set for:
 - BTT - read from "attributes.json" file, not allowed as an input
 - CRDS - reads sampling period from file name, allows input but this is superseded by filename value if present
 - GCWERKS - read from "process_gcwerks_parameters.json" file, allowed as an input

**Comment by rt17603** [comment]
PR #186 - standardised the value for unknown sampling period to "NOT_SET" and added this as an input for AQMesh, Glasgow_licor, Glasgow_picarro  (but not BTT where this is always read from a file).

**Comment by rt17603** [comment]
NOAA data
 - Within insitu data this often seems to be hourly with the "dataset_selection" attribute giving details for this (hourly - "all valid hours"). This also aligns well with the time stamps from the data.
 - For the flask data this often seems to be measured weekly with no sampling period indicated.
    - From digging a bit into the literature perhaps an approx value of "5 mins" for these samples may be appropriate? e.g. Atmospheric Methane Concentrations, the NOAA/CMDL Global Cooperative Flask, L. Paul Steele, Patricia M. Lang, Robert J. Sepanski, 1991, page A-9 references: 
    - > "Two pairs of flasks are exposed at CGO each week. One pair is taken with the portable sampler, and almost simultaneously a pair is flushed (5 min) and pressurised with air taken from a sampling stack similar in design"

Not looked into aircraft or core samples yet.
