### ISSUE TITLE
ICOS NRT data - extra files retrieved

### ISSUE THREAD

**Issue by joe-pitt** [openghg/openghg#864]
### What happened?

The ICOS Carbon Portal now appears to have each day's NRT data as a separate file (e.g. https://meta.icos-cp.eu/objects/LeTEFlcwYuuBsqWnMCHhm8b7) in addition to the whole timeseries as one file (e.g. https://meta.icos-cp.eu/objects/VWqk2M8VneKIKm-dVA2kUWAC). We only want to retrieve the latter. My code below still runs, and we seem to end up with the whole timeseries in the object store, but it now takes many hours to run because it retrieves all the individual files too.

### What did you expect to happen?

Ideally we would ignore the new single-day records so that the code runs as before.

### Minimal Complete Verifiable Example

```Python
from openghg.retrieve.icos import retrieve_atmospheric

site_list = ["BIR","CBW","CMN","GAT","HEL","HPB","HTM","IPR","IZO","JFJ",
             "JUE","KIT","KRE","LIN","LMP","LUT","NOR","OPE","OXK","PAL",
             "PRS","PUI","PUY","RUN","SAC","SMR","SNO","SSL","STE","SVB",
             "TOH","TRN","UTO","WAO","WES","ZEP","ZSF"]

for site in site_list:
    cp_data = retrieve_atmospheric(site=site,
                                   species = ["CO", "CO2", "CH4", "N2O"],
                                   force_retrieval=True,
                                   data_level=1,
                                   dataset_source="ICOS",
                                   update_mismatch="from_source")
```

### Environment

Python: 3.11.6

OpenGHG:
commit ec02f3dc37e7d706a824e5eec2de9ed28871f09b (HEAD -> devel)
Merge: 0d9638d0f 05dfd7a91
Author: Gareth Jones <8915182+gareth-j@users.noreply.github.com>
Date:   Fri Dec 15 11:47:45 2023 +0000

**Comment by gareth-j** [comment]
This may be related to #865
