### ISSUE TITLE
Search not returning expected data (model keyword used)

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#875]
### What happened?

`search_footprints(site="tac").results returns the following:

![Screenshot 2024-01-22 at 11 59 53](https://github.com/openghg/openghg/assets/37222223/4b325568-e781-4f8d-8db3-f9de799dc439)

`search_footprints(site="tac", model="NAME").results`

Does not return any search results.

### What did you expect to happen?

The second search should return the same as the first search.

### Anything else we need to know?

Set up
 - Multiple object stores within config but this data is currently within `paris_openghg_store`

### Environment

<details>

</details>

**Comment by joe-pitt** [comment]
I stumbled across this too. It looks like there has been a breaking change where model is now loaded and searched for as lower case. I'm investigating now...

**Comment by joe-pitt** [comment]
OK this is well beyond me - I've no idea what's going on with this database searching. But if you search in paris_openghg_store for
`retrieve.search_footprints(model="name")`
it returns one entry - a BSD fp that was loaded on 2024-01-08 and has model=name. All the other entries were loaded on earlier dates, and have model=NAME. Maybe this is one for the code retreat?

**Comment by rt17603** [comment]
Any updates on the status of this bug? Is this still happening with the latest object stores? And did we have a fix for this?

**Comment by joe-pitt** [comment]
I think this one is fixed. I will close but if anyone knows otherwise please reopen!
