### ISSUE TITLE
EDGAR v8 not accepted by transform_emissions_data function

### ISSUE THREAD

**Issue by qq23840** [openghg/openghg#880]
### What is your issue?

When attempting to regrid and standardise EDGAR v8 emissions data using the openghg.transform.transform_emissions_data function, passing edgar_version='8.0' raises a ValueError:

ValueError: Unable to infer EDGAR version. Please pass as an argument (one of ['v432', 'v50', 'v60'])

It looks like v8 just needs to be added into the list of known versions, defined in line 491 of  openghg/transform/emissions/_edgar.py. I'm not sure if this would have any other knock-on effects?

**Comment by brendan-m-murphy** [comment]
This is a duplicate of #568. I tagged that issue with "parsing/transform", so we can find it easily.
