### ISSUE TITLE
Catch chunking errors and give useful feedback

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#885]
We need to catch chunking errors and give the user a useful suggestion in how to fix it.

**Comment by SutarPrasad** [comment]
**For the following scenarios these can be temporary solutions for users:**

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/vq21425/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/vq21425/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


Sr | Scenario | Error Type | Solution
-- | -- | -- | --
1 | Files passed without chunks on   first run | Value Error : Inconsistent chunk   try using unify_chunks | Call   chunks={"time":100}
2 | Files   passed with chunks on time dimension | Value   Error : Inconsistent chunk on dim: lat | Calling chunks across {"time":100, "lat":100,   "lon":100}
3 | co2 files BSD   2015 | Value Error :   Inconsistent chunk | Sort the files and supply   chunks={'time': 100, 'lat': 100, 'lon': 100}



</body>

</html>

**Comment by gareth-j** [comment]
Closing as we're not encountering these errors now. Any errors that do arise we want to know about so don't want to catch.
