### ISSUE TITLE
When adding footprints does not currently differentiate for species

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#902]
### What happened?

When using `standardise_footprint`, the optional parameter `species` are not currently used to define a new datasource - `short_lifetime` key is used instead.

For example on BP1:
- /group/chemistry/acrg/LPDM/fp_NAME/MHD-10magl_UKV_hfo-1234yf_EUROPE_201701.nc
- /group/chemistry/acrg/LPDM/fp_NAME/MHD-10magl_UKV_hfo-1234zee_EUROPE_201612.nc

are added to the same datasource when they should create separate data sources.

### What did you expect to happen?

Adding the two files should have created two datasources but only creates one.

### Minimal Complete Verifiable Example

Running on BP1
```Python
# Add new data
from openghg.standardise import standardise_footprint
from pathlib import Path

directory = Path("/group/chemistry/acrg/LPDM/fp_NAME/EUROPE")

store = "user"

file_species1 = directory / "MHD-10magl_UKV_hfo-1234yf_EUROPE_201701.nc"
file_species2 = directory / "MHD-10magl_UKV_hfo-1234zee_EUROPE_201612.nc"


site = "MHD"
inlet = "10m"
metmodel = "UKV"
domain = "EUROPE"
model = "NAME"

species = "hfo-1234yf"

standardise_footprint(file_species1,
                      site=site,
                      inlet=inlet,
                      metmodel=metmodel,
                      domain=domain,
                      species=species,
                      model=model,
                      store=store)


species = "hfo-1234zee"

standardise_footprint(file_species2,
                      site=site,
                      inlet=inlet,
                      metmodel=metmodel,
                      domain=domain,
                      species=species,
                      model=model,
                      store=store)

# Search
from openghg.retrieve import search_footprints

footprints = search_footprints(store=store, site="mhd").results

print(footprints)
print(footprints["species"])
```

### Relevant log output

```Python
data_type site  ...                                           versions                        object_store
0  footprints  mhd  ...  {'v0': ['2016-12-01-00:00:00+00:00_2016-12-31-...  /user/work/rt17603/test_store_zarr

[1 rows x 25 columns]
0    hfo-1234zee
Name: species, dtype: object
```

### Anything else we need to know?

Probably better to use `species` as the keyword to use to distinguish data sources *rather than* `short_lifetime` (but setting the `short_lifetime` variable in the metadata is still very useful).

### Environment

<details>

</details>

**Comment by rt17603** [comment]
Can set a default for `species="inerrt"`. This also aligns with more recent changes for the NAME footprints.

**Comment by gareth-j** [comment]
Done with #932

**Comment by rt17603** [comment]
Not really closed yet as this is on `new_object_store` but not in devel yet - is linked against PR #831 so this should be closed automatically when this is merged.
