### ISSUE TITLE
New footprint formats

### ISSUE THREAD

**Issue by ag12733** [openghg/openghg#905]
### What is your issue?

New footprints will now be processed with a different format and filename.  An example footprint file is located in on BP1 under _shared/temp_anita_rachel/BSD-250magl_NAME_UKV_EUROPE_inert_201412.nc_

openghg needs to be able to ingest these new files and remain compatible with the old format.

**Comment by rt17603** [comment]
Thanks for the details - I've had a look over the new footprint file and get the gist of the changes to make.

A few questions:
 - For the high time resolution footprints (co2) was there an expectation that this would be renamed as well e.g. from "fp_HiTRes" to "srr_HiTRes"?
 - Was the inlet height attribute removed?
 - For the inert footprint linked (BSD-250magl_NAME_UKV_EUROPE_inert_201412.nc), would you expect the attribute `'loss_lifetime_hrs': `-9.0``? I'm comparing against the "BSD-250magl_UKV_EUROPE_201412.nc" filefile and I can see this used to be `'loss_lifetime_hrs': 'No loss applied'`.

**Comment by rt17603** [comment]
Note this should also applicable to provided flexpart footprints. The new name and flexpart footprints *should* be able to use the same parser when this has been created.
