### ISSUE TITLE
Cannot import data_manager

### ISSUE THREAD

**Issue by SutarPrasad** [openghg/openghg#913]
### What happened?

`from openghg.store import data_manager` raised following 
**error**:ImportError: cannot import name 'data_manager' from 'openghg.store' (/user/home/vq21425/openghg/openghg/store/__init__.py)

### What did you expect to happen?

Expected to import data_manager

### Anything else we need to know?

Change import on tutorials to `from openghg.dataobjects import data_manager` 

### Environment

<details>

</details>

**Comment by gareth-j** [comment]
`from openghg.store import data_manager` no longer appears in the codebase. Closing.
